### ISSUE TITLE
Play 2.5 compatibility

### ISSUE THREAD

**Issue by jtammen** [pac4j/play-pac4j#101]
Seems as if some APIs have been removed in [Play 2.5](https://www.playframework.com/documentation/2.5.x/Migration25) – would be nice to have a new version of play-pac4j compatible to Play 2.5! (-:

**Comment by leleuj** [comment]
Sure. We just released a version 2.1.0 with the new security filter. Soon there will be a new version based on pac4j v1.9.
Let's do a v2.2.0 for Play 2.5. Would you mind giving it a try? I just created a branch 2.1.x and updated the master to 2.2.0 for that.
The demos have been updated accordingly.

**Comment by zdavep** [comment]
Running local builds from master gives the following for me:

> ExecutionError: java.lang.NoClassDefFoundError: play/mvc/Results$StatusHeader

Built using master branches of play-pac4j (2.2.0-SNAPSHOT) and pac4j (1.9.0-SNAPSHOT).

**Comment by leleuj** [comment]
Thanks for the feedback. You should just try to move to Play 2.5 and still use pac4j 1.8.6 for now. It will be easier to just upgrade one of the two frameworks.

**Comment by zdavep** [comment]
I get the same error as above with 1.8.6 (which is the reason I tried master branches).  The problem seems to stem from the fact that 'StatusHeader' is now a standalone class in Play 2.5 (and no longer under 'Results').  If I remove pac4j from my project, I don't see the error.

**Comment by leleuj** [comment]
I'm not surprised that the new Play 2.5 version introduces some breaking changes and I think it can be easily fixed.
My main concern is about strategy: I think it's better to upgrade to pac4j 1.9 first and release a 2.2 version. And then, upgrade to Play 2.5 (with pac4j 1.9) and release a 2.3 version.
I will upgrade to pac4j 1.9 in the next days.

**Comment by zdavep** [comment]
Sounds good.  Thank you very much for the feedback. :100:

**Comment by nielsdraaisma** [comment]
I've managed to get this module working (as in, no longer throwing the error above) with Play 2.5, fork available at https://github.com/nielsdraaisma/play-pac4j

Further stability is unknown since I've only just started using this library and can't easily go back to older play versions.

**Comment by leleuj** [comment]
Thanks for your help. Though, the priority is given to the upgrade towards pac4j v1.9 which will change several things (https://github.com/leleuj/play-pac4j/tree/play-102). So I would not spend too much time on the Play version upgrade before the play-pac4j version 2.2 is released.

**Comment by nielsdraaisma** [comment]
I've noticed you've merged in the branch you mentioned above. Are you expecting more work to be done on that side, or would now be a good time to start looking at play 2.5 support.

I'm happy to retrofit my fork on the current codebase if it's not a waste of time :)

**Comment by leleuj** [comment]
https://github.com/pac4j/pac4j/issues/558 is still on the path of the 1.9 release, but after that, I'll be able to release pac4j and play-pac4j and we'll be able to tackle the Play 2.5 upgrade.

So, currently, we have:
- branch 2.1: Play 2.4 + pac4j 1.8 -> released
- master (2.2): Play 2.4 + pac4j 1.9 -> in progress

Though, I realized this issue has been opened a few months ago so if you have time and will, I can update master to 2.3 and create a 2.2 branch on which you could upgrade to Play 2.5 while keeping pac4j v1.8, you would need to do that again after the upgrade to pac4j v1.9 as well as on the demos (https://github.com/pac4j/play-pac4j-scala-demo & https://github.com/pac4j/play-pac4j-java-demo).

What do you think?

**Comment by leleuj** [comment]
Hold on.

I realized we already have this PR: https://github.com/pac4j/play-pac4j/pull/106, by @andriykuba which could be used if targeted to the right branch.

I just created the 2.2 branch: @andriykuba, can you submit a new PR to this branch? If so, @nielsdraaisma : could you review the PR ?

**Comment by andriykuba** [comment]
@leleuj: done

**Comment by leleuj** [comment]
@andriykuba : thanks

**Comment by leleuj** [comment]
Done for play-pac4j v2.2 (pac4j v1.8): to be done for play-pac4j v2.4 (pac4j v1.9)

**Comment by wwbakker** [comment]
Thanks. 
I can't find it in maven central yet though. Will it be in there soon?
http://search.maven.org/#search%7Cga%7C2%7Cpac4j

**Comment by leleuj** [comment]
Snapshots are only available in the Maven snapshots repository: https://github.com/pac4j/play-pac4j#development till I release the project as the 2.2.0 release (available in the Maven central repo).

**Comment by champloo** [comment]
Would it be possible to release the latest changes on 2.2.x branch to the Maven snapshots repo? The version that is currently in the snapshots repo does not work with Play 2.5.

**Comment by leleuj** [comment]
It should be ok now.

**Comment by champloo** [comment]
Great, thank you!

**Comment by leleuj** [comment]
@andriykuba : I released the new play-pac4j v2.3.0 based on the new pac4j v1.9.0, but it is still based on Play 2.4. Would you mind upgrading it to Play 2.5? As well as the demos? Thanks

**Comment by andriykuba** [comment]
@leleuj: I will do it

**Comment by andriykuba** [comment]
@leleuj: please, verify my pull requests

**Comment by leleuj** [comment]
Thanks for the pull requests and sorry if I was unclear, but they must target the master (which is in version 2.4.0-SNAPSHOT while the 2.3.x branch will stay in Play 2.4 and pac4j v1.9)

**Comment by andriykuba** [comment]
No problem, I have moved them to master.

**Comment by leleuj** [comment]
Many thanks. Merging, except the Scala demo where the build is broken...

**Comment by andriykuba** [comment]
I will look, my local has been built fine. 

Could it be because the "2.4.0-SNAPSHOT" in the sonatype snapshots repository still the old one, so scala demo takes wrong pac4j ?

**Comment by leleuj** [comment]
I think the right 2.4.0-SNAPSHOT version has been deployed to Sonatype repo: https://oss.sonatype.org/content/repositories/snapshots/org/pac4j/play-pac4j/2.4.0-SNAPSHOT/ (I see one from this "morning" matching the latest build: https://travis-ci.org/pac4j/play-pac4j/builds/137747635)
