### ISSUE TITLE
Can't get current client from HttpActionAdapter

### ISSUE THREAD

**Issue by ArkadyKarev** [pac4j/play-pac4j#103]
Hi! We using different direct clients for different platforms (mobile, web), and therefore it's important to obtain current client from HttpActionAdapter. For example, in case with mobile app (ParameterClient), I want to send json for unauthorized client, and for the web version (CookieClient) I need to send redirect to login page.
RequiresAuthenticationAction has list of currentClients it the 'unauthorized' method, but it not passing to 'adapt' method of HttpActionAdapter (http://puu.sh/nSEvC/5f6759e1fc.png). Is it possible to extend interface HttpActionAdapter with a List<Client> parameter?

**Comment by leleuj** [comment]
Hi,

The idea behind the HttpActionAdapter (which is also used in other pac4j
implementations) is to deal only with proper HTTP responses generations /
transformations.

So the protected method is meant to be overriden in subclasses to have the
appropriate behaviour. Just let me know if that works smoothly or if we
need to revisit this for pac4j v1.9.

Thanks.
Best regards,
Jérôme




2016-03-24 22:25 GMT+01:00 ArkadyKarev <notifications@github.com>:

**Comment by ArkadyKarev** [comment]
Thanks you for quick reply, Jérôme!

Dealing with proper HTTP responses from HttpActionAdapter is nice and clear. May be in our case we need something like several different HttpActionAdapters for different implementation of DirectHttpClient (one HttpActionAdapter per each direct client). But I think that it's more complicated solution, than having info about current clients from HttpActionAdapter. As I wrote before, I would like to do different actions, when RequiresAuthenticationAction 'says' that client is unauthorized (depending on Client implementation). Actually, primary goal of that, is ability to send JSON with 401 status code for mobile application clients (that uses ParameterClient), and to send 302 status code for redirecting users to signin/signup page for web clients (that uses CookieClient). Could you give me advice or workaround how to achieve this, please? Ofcourse we always can handle json with 401 'unathorized' code in web clien too, like in mobile apps, and change windows.location to /signup, but sending 302 redirect to login page it's more proper way, I think. Or am I wrong? :) Your opinion very appreciated!

Thank you,
Arkady

**Comment by leleuj** [comment]
Hi,

In fact, this behaviour already exists if you are not authenticated:
- if you use an indirect client (let's say FacebookClient), you'll be
redirected to the Facebook login page; AJAX request are also detected and a
401 error is returned in that case
- if you use a direct client, a 401 error page will be returned as
credentials should have been passed along the request and the
authentication should have already occured.

So I think what you need here is an IndirectCookieClient: it should be a
copy/paste from the CookieClient, but inheriting from IndirectHttpClient
and with the appropriate redirection.

Thanks.
Best regards,
Jérôme





2016-03-25 9:33 GMT+01:00 ArkadyKarev <notifications@github.com>:

**Comment by ArkadyKarev** [comment]
Brilliant!
Exactly that what looking for. Thank you, Jérôme! Everything works smoothly. But I've to write a little workaround, because IndirectHttpClient has _extractor_ field with UsernamePasswordCredentials generic type. May I make pull request with the following code into one of pac4j repos (please point me at one, if you think that its good idea), and with changing UsernamePasswordCredentials type of generic to HttpCredentials in IndirectHttpClient.extractor field?

```
package security;

import org.pac4j.core.client.BaseClient;
import org.pac4j.core.client.ClientType;
import org.pac4j.core.client.RedirectAction;
import org.pac4j.core.context.WebContext;
import org.pac4j.core.exception.CredentialsException;
import org.pac4j.core.exception.RequiresHttpAction;
import org.pac4j.core.util.CommonHelper;
import org.pac4j.http.client.indirect.IndirectHttpClient;
import org.pac4j.http.credentials.TokenCredentials;
import org.pac4j.http.credentials.authenticator.TokenAuthenticator;
import org.pac4j.http.credentials.extractor.CookieExtractor;
import org.pac4j.http.credentials.extractor.Extractor;
import org.pac4j.http.profile.creator.ProfileCreator;

/**
 * Created by arkady on 25/03/16.
 */
public class IndirectCookieClient extends IndirectHttpClient<TokenCredentials> {
	private String realmName = "authentication required";
	private String cookieName;
	private String loginUrl;
	protected Extractor<TokenCredentials> extractor;

	public IndirectCookieClient() {
	}

	public IndirectCookieClient(final String cookieName, final String loginUrl, final TokenAuthenticator cookieAuthenticator) {
		setAuthenticator(cookieAuthenticator);
		this.cookieName = cookieName;
		this.loginUrl = loginUrl;
	}

	public IndirectCookieClient(final String cookieName, final String loginUrl, final TokenAuthenticator cookieAuthenticator,
						final ProfileCreator profileCreator) {
		setAuthenticator(cookieAuthenticator);
		setProfileCreator(profileCreator);
		this.cookieName = cookieName;
		this.loginUrl = loginUrl;
	}

	@Override
	protected void internalInit(WebContext context) {
		CommonHelper.assertNotBlank("cookieName", this.cookieName);
		CommonHelper.assertNotBlank("loginUrl", this.loginUrl);
		extractor = new CookieExtractor(this.cookieName, getName());

		//wa instead of super.internalInit(context), because we need to use extractor, with different generic type
		CommonHelper.assertNotNull("authenticator", getAuthenticator());
		CommonHelper.assertNotNull("profileCreator", getProfileCreator());
		//super.internalInit(context);
	}

	@Override
	protected boolean isDirectRedirection() {
		return true;
	}

	@Override
	protected RedirectAction retrieveRedirectAction(WebContext context) {
		return RedirectAction.redirect(this.loginUrl);
	}

	@Override
	protected TokenCredentials retrieveCredentials(WebContext context) throws RequiresHttpAction {
		final TokenCredentials credentials;
		try {
			// retrieve credentials
			credentials = extractor.extract(context);
			logger.debug("credentials : {}", credentials);

			if (credentials == null) {
				throw RequiresHttpAction.unauthorized("Requires authentication", context, this.realmName);
			}

			// validate credentials
			getAuthenticator().validate(credentials);
		} catch (final CredentialsException e) {
			throw RequiresHttpAction.unauthorized("Requires authentication", context,
					this.realmName);
		}

		return credentials;
	}

	@Override
	protected BaseClient newClient() {
		final IndirectCookieClient newClient = new IndirectCookieClient();
		newClient.setCookieName(this.cookieName);
		return newClient;
	}

	@Override
	public ClientType getClientType() {
		return ClientType.COOKIE_BASED;
	}

	public String getCookieName() {
		return cookieName;
	}

	public void setCookieName(String cookieName) {
		this.cookieName = cookieName;
	}

	public String getLoginUrl() {
		return loginUrl;
	}

	public void setLoginUrl(String loginUrl) {
		this.loginUrl = loginUrl;
	}
}
```

**Comment by leleuj** [comment]
Good proposal, but the `IndirectHttpClient` has already been refactored to something more generc in the `pac4j-core` module and the problem has been fixed: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/client/IndirectClient2.java#L29

**Comment by ArkadyKarev** [comment]
Very nice! So what about IndirectCookieClient?

**Comment by leleuj** [comment]
That's possible: the appropriate `RedirectActionBuilder` should be define according to the needs. Would you mind taking care of that?

**Comment by ArkadyKarev** [comment]
Jérôme, actually I was wrong, when I said that everything works fine. RequiresAuthenticationAction class inside internallCall method makes decision to use or not session flag
`final boolean useSession = useSession(context, currentClients);` and just a little below, if useSession is 'true', it uses Pac4jConstants.USER_PROFILE constant to obtain UserProfile from session store. Could you give me a hint, or just point at right way, how I can put UserProfile into SessionStore? Or probably another solution, how I can implement cookie-based client with redirectUrl? I think may be I could extend FormClient and override something, but I would like to use long-life cookie-based tokens, with custom name. I didn't find any way to do that.

**Comment by leleuj** [comment]
You must keep in mind the two kinds of clients:
- indirect client are used for remote authentication that occurs once and need a callback endpoint, they are stateful 
- direct clients are used when authentication happens on every request (credentials must be provided on every request), they are stateless. A cache can be used for performance reasons.

The `useSession` flag is computed according to the clients configuration: if you have an indirect client, we'll look at the session while we don't for direct clients. If you need to use the session, either you need an indirect client or you need to save the profile in the context by yourself: `new ProfileManager(context).save(true, profile)`.

In the next play-pac4j version (master, v2.2), you'll have multiple profiles and the ability to control if profiles are saved in session even for direct clients.
