### ISSUE TITLE
Invalid JWT's generated.

### ISSUE THREAD

**Issue by Wicked0ne** [pac4j/play-pac4j#104]
Using the provided examples, when you use http://play-pac4j-java-demo.herokuapp.com/jwt.html it will generate a token, but it does not seem to be a valid JWT token. Trying to decode the token using one of the online JWT decoders results in errors.

**Comment by leleuj** [comment]
Hi,

By default, JWT tokens are encrypted as they contain user profiles with
potentially sensitive data, so I'm not surprised you can't decode them.

Though, you can disable encryption using the appropriate constructor with
the JwtGenerator.

Thanks.
Best regards,
Jérôme


2016-03-28 0:45 GMT+02:00 Wicked0ne <notifications@github.com>:
