### ISSUE TITLE
Race conditions on CallbackController

### ISSUE THREAD

**Issue by rsemlal** [pac4j/play-pac4j#105]
The code of the redirection method in the CallbackContoller is the following:
```protected Result redirectToOriginallyRequestedUrl(final WebContext context) {
        final String requestedUrl = (String) context.getSessionAttribute(Pac4jConstants.REQUESTED_URL);
        logger.debug("requestedUrl: {}", requestedUrl);
        if (CommonHelper.isNotBlank(requestedUrl)) {
            context.setSessionAttribute(Pac4jConstants.REQUESTED_URL, null);
            return redirect(requestedUrl);
        } else {
            return redirect(this.defaultUrl);
        }
    }```

The "issue" here is that `Pac4jConstants.REQUESTED_URL` is stored in session and gets deleted as soon as a redirection is correctly performed.

We have in our application a case where an upstream application needs to call our api twiceat startup  => both requests get redirected the first time => the callback route is called on our api twice, the first time the REQUESTED_URL is still in session and the http call gets redirected to the correct originally requested uri, but the second time the value of the original request is wiped out from the session so the user gets redirected to a wrong url.

For me it seems like a race condition happening on the callback call, is this something that can (should?) be solved on your side somehow?

**Comment by leleuj** [comment]
I'm not sure to fully understand your use case: the `CallbackController` is meant to finish an authentication started at a remote identity provider, it should be called once and then, the user is authenticated and redirected to the originally requested url.

Can you elaborate a little more?

**Comment by rsemlal** [comment]
Hi,

Sorry i was a bit unclear, so:
Currently we have developped a webapp (app A) that requires authentication, so when an unauthenticated user tries to access the route /web (for example) he gets redirected to the login page, and if the login is successful he is redirected back to the requested page (/web in this example)

The thing is that end user do not load the /web directly, instead they have access to another app (app B) that loads /web TWICE on stratup (apparently it is needed for some visual effect)

Since the two calls to /web are done at the same time, if the user is unauthenticated at startup, both calls gets redirected to the identity provider, then /callback on app A is called twice. The first time, after the /callback call, the redirection to the original requested url (/web) succeeds, then this original requested url is removed from the session, the second time the callback is called it doesn't find this information in the session anymore

Hope it is a bit more clear now

**Comment by leleuj** [comment]
OK. I get it now. This is a very specific use case so I think the best option for you is to override the `CalbackController` with your own controller and copy/paste the `redirectToOriginallyRequestedUrl` method and remove the cleaning of the originally requested url: `context.setSessionAttribute(Pac4jConstants.REQUESTED_URL, null);`

It should do the job, although I fear some side effects.
