### ISSUE TITLE
getRequestCookies NullPointerException

### ISSUE THREAD

**Issue by entropicdrifter** [pac4j/play-pac4j#128]
Hi,
I'm trying to use a Cookie based Direct Authentication scheme, but the getRequestCookies() method inside PlayWebContext keeps throwing NullPointerExceptions, specifically due to the httpCookie.maxAge() and httpCookie.domain() calls.

Since this method is inside the PlayWebContext class, it is very difficult to extend a single class in order to override this method. 

Apparently it is part of the Play team's intentional design to leave some of these fields null under certain circumstances:
https://playframework.com/documentation/2.5.x/api/java/play/mvc/Http.Cookie.html#domain--

**Comment by leleuj** [comment]
In fact, I have never tested the cookies support. And I agree it must be changed at the `PlayWebContext` level.

Would you mind submitting a pull request for that? Thanks

**Comment by leleuj** [comment]
Thank you very much
