### ISSUE TITLE
Cookies with max-age -1 expire immediately 

### ISSUE THREAD

**Issue by othrayte** [pac4j/play-pac4j#135]
I noticed when trying to use the pac4j CSRF token generation with Play 2.5 that cookies created by the `CsrfTokenGeneratorAuthorizer` expire immediately.

These cookies have max-age set to -1 (the default). The issue appears to be due to a change from Play 2.0 to Play 2.1 where the max-age value they use to indicate a transient/session cookie changed from -1 to `null`/`None`. The pac4j `PlayWebContext` seems to miss converting the -1 max-age value to null when creating Play Cookies in `PlayWebContext.addResponseCookie()`. I noticed however that `PlayWebContext.getRequestCookies()` does convert `null` back into -1 as changed recently in #128.

It is also possible that I'm misunderstanding how the CSRF tokens are supposed to be used (I'm assuming that I should be able to read them client-side and send them back).

**Comment by leleuj** [comment]
Your understanding is correct: the CSRF token is supposed to be saved in a **session** cookie (and not expire immediately).

So there is a problem with Play (most frameworks handle that properly)

I guess the work started with #128 must be improved: we should check the max-age before setting a cookie and defaults to -1 if null (`PlayWebContext`).

Would you mind submitting a pull request for that on branch 2.3.x, 2.4.x and 2.5.x? Thanks

**Comment by leleuj** [comment]
Taking another look at this, I'm not sure to understand how the max-age can be set to `null`.  The pac4j `Cookie`  has: `private int maxAge = -1;` and the Play cookie is built directly from this value in the `addResponseCookie` method.

More details would be appreciated. This blocks the 2.3.1 and 2.4.1 releases.

**Comment by othrayte** [comment]
So my understanding is that maxAge of -1 in pac4j should be a session cookie. In Play a session cookie is a cookies with a maxAge set to `null`. So my plan was to convert pac4j cookies with the default -1 maxAge to Play cookies with `null` maxAge. The recent changes in #128 make the opposite conversion true, Play cookies with `null` maxAge become pac4j cookies with maxAge set to -1. If this is correct then I should be able to make a PR.

**Comment by leleuj** [comment]
Yes, `maxAge` of -1 in pac4j is a session cookie. But it's true generally.

Currently, we do:

```java
response.setCookie(cookie.getName(), cookie.getValue(), cookie.getMaxAge(), cookie.getPath(),
                cookie.getDomain(), cookie.isSecure(), cookie.isHttpOnly());
```

So we pass the `cookie.getMaxAge()`, and in Play, the `maxAge` is an `Integer`.

Why passing -1 does not work? You want to check the value of the `cookie.getMaxAge()` and pass `null` if it's -1?

**Comment by othrayte** [comment]
For some reason Play's `Http.Cookie`, which is what is used in [`Http.Response.setCookie()`](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/java/play/mvc/Http.java#L1895) uses the value `null` for session cookies and interprets all negative values (including -1) as intending for the cookie to immediately expire.

So yes, I was thinking that -1 should become `null` when passing to Play.

[Class Http.Response](https://www.playframework.com/documentation/2.5.0/api/java/play/mvc/Http.Response.html)
setCookie()
> maxAge - Cookie duration (null for a transient cookie and 0 or less for a cookie that expires now)

[Class Http.Cookie](https://www.playframework.com/documentation/2.6.x/api/java/play/mvc/Http.Cookie.html)
> public java.lang.Integer maxAge()
> Returns:
> the cookie expiration date in seconds, null for a transient cookie, a value less than zero for a cookie that expires now

**Comment by othrayte** [comment]
Also, at some point internally I found that Play converts the cookie again and the `Integer` is converted back to an `int`, at which point they use `Integer.MIN_VALUE`, it was last week that I found this but I think it is [here](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/mvc/Cookie.scala#L116). For reference play omits the `maxAge` and `expires` [here to create a session cookie](https://github.com/playframework/playframework/blob/master/framework/src/play-netty-utils/src/main/java/play/core/netty/utils/ServerCookieEncoder.java#L87).

**Comment by leleuj** [comment]
Thanks for the explanations. I feel that the Play source code could be improved on that.

So yes, we should change `cookie.getMaxAge()` by  `cookie.getMaxAge() == -1 ? null : cookie.getMaxAge()`, shouldn't we?

On that basis, you can submit PR for 2.3.x and 2.4.x branches as well as the master? It should be straightforward...

**Comment by othrayte** [comment]
Have already started on the changes, that was the easy bit, I'm working on verifying the change but having some difficulty getting my local build of play-pac4j to run in my project to test it, does it matter which version of pac4j-core I use to test play-pac4j 2.4 (which is currently what my project uses)? If not I'll probably figure it out tomorrow anyway.

**Comment by leleuj** [comment]
About which versions of `pac4j-core` you can use, I tried to sum up everything here: http://www.pac4j.org/docs/backward-compatibility.html

With `play-pac4j` v2.4.x, you can use pac4j-* v1.9.x libraries.

**Comment by othrayte** [comment]
Ok, that was simple I just needed to use 1.9.1 due to the `validate()` change.

I will have the PR in shortly, but one other thing we needed to do to use the CSRF tokens was set the cookies path to `/` as my js code otherwise couldn't see the cookie when the cookie was returned from an ajax request. Is that something that would normally need to be done for CSRF token cookies or is that something odd about how I have the js and api routes setup?

**Comment by leleuj** [comment]
Regarding the "maxAge issue", I merged the PR for master and 2.4.x branch, but the PR for 2.3.x branch fails at compilation.

About the `/` path, the CSRF cookie should normally be set on the context path of the web app. I guess we are talking about the `CsrfTokenGeneratorAuthorizer` component and indeed, there is no way to set the cookie domain or path. The domain used is the `context.getServerName()` and the path is the default one.
I guess we should allow defining the domain, path, isSecure, isHttpOnly, ... for the CSRF cookie.

What was the path used by default in your case? Why was it a problem? Can you elaborate on this? Thanks

**Comment by othrayte** [comment]
Re: cookie path issues,

The cookies by default had paths that reflected the request, so `/api/x/y/z` had cookies with the path `/api/x/y/z`.

It turned out that cookies with the url and cookie path `/api/x/y` were not being stored by the browser but cookies with the url and cookie path `/api/x` or `/x` were being stored. Most of this testing was done with ajax requests and I haven't yet determined if this in an ajax specific issue.

Given that the cookie path indicates what paths should see the cookie I think we probably need it to be `/` anyway so that the entire app can use the cookie. FYI, the app is on the paths like `/`, `/page1`, `/subsection/page2` and the apis are on `/api/x/y`.

I'm not sure if controlling all those parts of the CSRF token cookie are useful to just my situation or are generally useful.

**Comment by leleuj** [comment]
This is a use case I didn't think about. You're right, the path should be settable and have a default value of `/`.

And we should do the same for the domain: it should be settable and have a default value of `context.getServerName()`. Same for the `isSecure` property (`false` by default) and `ishttpOnly` (`false`  by default).

Would you mind adding that to the PR you prepare for: #137 ? Thanks

**Comment by leleuj** [comment]
Replaced by: https://github.com/pac4j/pac4j/issues/673
