### ISSUE TITLE
2.4.1-SNAPSHOT incompatible with pac4j 1.9.0

### ISSUE THREAD

**Issue by entropicdrifter** [pac4j/play-pac4j#136]
It seems that, most likely due to my meddling, the current snapshot of 2.4.x only supports pac4j 1.9.1. 
When I attempt to use it with 1.9.0, it throws the following exception:
`java.lang.AbstractMethodError: Method org/pac4j/ldap/credentials/authenticator/LdapAuthenticator.validate(...) is abstract`

This happens with the JWT authenticator too, so I assume it's a general issue.

As I said though, everything seems to be working perfectly with play-pac4j 2.4.1-SNAPSHOT and pac4j 1.9.1, so if you want you could just change the documentation and mark it resolved.

**Comment by leleuj** [comment]
I just wrote: http://www.pac4j.org/docs/backward-compatibility.html It should make things clearer. Just let me know.

I'll update the README by the way.
