### ISSUE TITLE
CsrfAuthorizer authorises all requests after session token expires

### ISSUE THREAD

**Issue by othrayte** [pac4j/play-pac4j#137]
The `CsrfAuthorizer` seems to consider not having a `sessionToken` (`== null`) as authorized if either parameter or header token are missing (`== null`). As I only set the header token results in all requests after the token expires as being authorized.

So far the work around has been to create a custom `CsrfAuthorizer` that additionally checks that the `sessionToken` is not `null` at [CsrfAuthorizer.java#L47](https://github.com/pac4j/pac4j/blob/f8ef2f3288001773423c878769a6b0dd7c10a5e0/pac4j-core/src/main/java/org/pac4j/core/authorization/authorizer/csrf/CsrfAuthorizer.java#L47).

Looking into why the `sessionToken` was `null` revealed that the `PlayCacheStore` returns `null` if requesting the `sessionToken` after it has expired.

**Comment by leleuj** [comment]
You're right: it's more a pac4j issue than a specific Play one. We should check that the `sessionToken` is not `null` either.

Would you mind submitting a PR for that (on the pac4j project)? Thanks

**Comment by leleuj** [comment]
Replaced by: https://github.com/pac4j/pac4j/issues/673
