### ISSUE TITLE
CSRF validation fails with form-posted parameter

### ISSUE THREAD

**Issue by djriffel** [pac4j/play-pac4j#142]
I'm not sure if I'm missing something here, or if the library is erroneously dropping the CSRF parameter from a form-body post. I always get forbidden when using the "csrfCheck" authorizer when coming from a form posting action that was wrapped with a "csrfToken" authorizer.

Here's what I found in my digging:

When using the org.pac4j.play.scala.Security.Secure() method, the WebContext is getting created via the RequestHeader constructor method, when called on line 78 of Security.scala. Following the trail, you can see the request body (and thus the csrf in the form parameters) is getting dropped when instantiating this web context. 

Security.scala line 78 leads to org.pac4j.play.PlayWebContext.java line 50:

```
JavaHelpers$.MODULE$.createJavaContext(requestHeader), sessionStore);
```

..which leads to play.core.j.JavaHelpers.scala line 85:

```
new JRequestImpl(req)
```

..which brings us to play.mvc.Http.java line 678 ("this.underlying" refers to the underlying Request instance of the RequestImpl class, which would have all the body parameters. When not supplied, we are getting only the header data):

```
this.underlying = null;
```

I was able to fix this issue by changing how the WebContext was instantiated in the Security trait. I'm not sure if there's an easier way to accomplish this, as the documentation is either very sparse on converting from Scala to Java request classes, or my google-fu is severely failing me.

In org.pac4j.play.scala.Security.scala on line 78, replace `val webContext = new PlayWebContext(request, playSessionStore)` with the following:

```
val javaBodyContent = request.asInstanceOf[Request[AnyContent]].body.asFormUrlEncoded
  .getOrElse(Map.empty[String, Seq[String]])
  .map(field => field._1 -> field._2.toArray)  // Make field values Java-friendly
  .asJava

val javaBody = new RequestBody(javaBodyContent)
val jRequest = Request(request, javaBody)
val jContext = JavaHelpers.createJavaContext(jRequest)

val webContext = new PlayWebContext(jContext, playSessionStore)
```

For your reference, I am using Play 2.5.8 with play-pac4j 2.5.0 and pac4j-oidc 1.9.2.

**Comment by leleuj** [comment]
I haven't checked it by myself, but I can only believe you because converting from Scala to Java is painful.

Woud you mind submitting a PR for that?

Can you create a unit test or add a CSRF check on the form post we have on the demo: https://github.com/pac4j/play-pac4j-scala-demo to confirm the fix?

Thanks

**Comment by djriffel** [comment]
I think I can put something together in the next 1-2 weeks. I'll let you know when I get a PR together.

**Comment by leleuj** [comment]
I was about to remind you about this issue. Thanks

**Comment by leleuj** [comment]
Any update on this?

**Comment by leleuj** [comment]
I now reproduce your issue with the Java demo: https://github.com/pac4j/play-pac4j-java-demo/commit/845955492ca929edfb626dcb4a6156923d10307b I will take a look at your fix

**Comment by vjkoskela** [comment]
Hi, not sure if this is related, but I would like to configure the Pac4J ```CallbackController``` to enforce the Play standard CSRF (e.g. as enabled via ```@RequireCSRFCheck```) on POST. Is this accomplished by adding the csrfAuthorizer as shown in your patch to play-pac4j-java-demo above?

**Comment by leleuj** [comment]
The pac4j CSRF and the Play CSRF are two different mechanisms, not related.

**Comment by djriffel** [comment]
@leleuj sorry for the delay on this, if you want I can get a PR done this week for this fix (if you haven't already started on it).

**Comment by leleuj** [comment]
Please go ahead.

**Comment by djriffel** [comment]
Added PR for the fix as well as the CSRF example. I didn't add a unit test, as I was unsure how to grab the token out of the response to test the result of the "csrfToken" authorizer index page. (I think this might be stored in the cache under the pac4j session, but I couldn't figure out how to get it)

**Comment by leleuj** [comment]
Your fix works, but only if you use the `Secure` function and not the `SecurityFilter`: can you move your logic into the constructor of the `PlayWebContext`: https://github.com/pac4j/play-pac4j/blob/master/src/main/java/org/pac4j/play/PlayWebContext.java#L55? Thanks

**Comment by djriffel** [comment]
Seems that implementing similar Request building code in Java is even more difficult. I'm getting a noSuchMethodError on trying to call play.api.mvc.Request$.MODULE$.apply(RequestHeader, RequestBody), even though it worked fine when called with the same parameter types using Scala.

It might take some time to go through this and try debugging why it's having issues.

**Comment by leleuj** [comment]
In that case, can you just copy / paste this logic inside the `SecurityFiler` as well?

**Comment by leleuj** [comment]
@djriffel : Any update on this? Do you need some help?

**Comment by leleuj** [comment]
Taking a closer look at this, I realize that the body is not available on the `RequestHeader` object, so your solution does not apply here. Passing the token as a GET parameter does the job.

I'm closing this issue. Feel free to reopen it if you want.
