### ISSUE TITLE
Create a `PlayCookieStore`

### ISSUE THREAD

**Issue by leleuj** [pac4j/play-pac4j#146]
based on the Play native session (in a cookie).

**Comment by leleuj** [comment]
The Play session cookie is only signed, not encrypted. So data can not be tampered, be read. This might not be a suitable solution if we don't use an encryption layer in addition to the signature.

**Comment by entropicdrifter** [comment]
What if you put a signed and encrypted token inside the Play session cookie as a value? 
If you did it that way, couldn't you just wrap a JwtGenerator and use [this method](https://github.com/pac4j/pac4j/blob/master/pac4j-jwt/src/main/java/org/pac4j/jwt/profile/JwtGenerator.java#L51)?
Of course you'd have to decrypt it from there, but that shouldn't be too difficult, right?

**Comment by leleuj** [comment]
I have always been reluctant to have clear data in the Play cookie, but using JWT is a good idea.

We should clear the profile from the sensitive data (for size and security): https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/profile/UserProfile.java#L329 and then, encrypt it with the `JwtGenerator` and decrypt it using the `JwtAuthenticator`.

**Comment by leleuj** [comment]
Yes. Go ahead
