### ISSUE TITLE
Capability to set the SecurityLogic

### ISSUE THREAD

**Issue by leleuj** [pac4j/play-pac4j#151]
pac4j v1.9.3 has been released with a `SecurityLogic` property in the `Config` object

**Comment by leleuj** [comment]
@richard77 : this is for you

**Comment by richard77** [comment]
Thanks!
Op do 20 okt. 2016 om 07:27 schreef LELEU Jérôme <notifications@github.com>

**Comment by leleuj** [comment]
A fairly easy one: https://github.com/pac4j/play-pac4j/pull/152
