### ISSUE TITLE
Possible FormClient Initialization vs Validation Bug

### ISSUE THREAD

**Issue by vjkoskela** [pac4j/play-pac4j#154]
Terrific library, looks very likely to acceleration our AuthN/Z needs. However, either I am misunderstanding something from the play demo (https://github.com/pac4j/play-pac4j-java-demo/blob/master/app/modules/SecurityModule.java) or there seems to be an initialization vs validation bug with FormClient (https://github.com/pac4j/pac4j/blob/master/pac4j-http/src/main/java/org/pac4j/http/client/indirect/FormClient.java).

The exception I get on form sign-in is:
```
2016-10-23 01:22:58,130 application-akka.actor.default-dispatcher-3 [ERROR] global.ErrorHandler : name="log", line="51", file="ErrorHandler.java", class="class global.ErrorHandler", message="error processing request", request="POST /auth/callback?client_name=FormClient" java.util.concurrent.CompletionException: org.pac4j.core.exception.TechnicalException: redirectActionBuilder cannot be null
```

The form client's ```internalInit``` method _first_ calls ```super.internalInit(context)```; therefore this happens before ```FormClient``` calls ```setRedirectActionBuilder``` and ```setCredentialsExtractor```. This is important because the parent class of ```FormClient``` is ```IndirectClientV2``` which asserts in its ```internalInit``` that ```redirectActionBuilder``` and ```credentialsExtractor``` are not null.

I recommend moving the two setter calls in ```FormClient``` above the call ```super.internalInit(context)```.

Versions:
* Play 2.5.9
* Pac4j 1.9.4
* Play Pac4j 2.5.0

**Comment by leleuj** [comment]
It works for me: can you check you really have the `pac4j-http` library in version 1.9.4?

**Comment by vjkoskela** [comment]
Yes, I do have the pac4j-http 1.9.4; however, it looks like play-pac4j 2.5.0 was bringing pac4j-core 1.9.2. Forcing that dependency to 1.9.4 resolves the issue. Apologies for not catching that. Thanks!

**Comment by leleuj** [comment]
No problem. Since version 2.0.0, things will be easier: http://www.pac4j.org/docs/backward-compatibility.html vs http://www.pac4j.org/1.9.x/docs/backward-compatibility.html
