### ISSUE TITLE
Play CSRF on CallbackController

### ISSUE THREAD

**Issue by vjkoskela** [pac4j/play-pac4j#155]
Is there an existing way to configure the CallbackController POST to enforce the Play standard CSRF? If not, would you be open to adding such a feature? I can contribute some code if you have any thoughts on where to start with this. Also, I'm open to alternatives if you have any best-practice recommendations in this regard.

Thanks,
Ville

**Comment by leleuj** [comment]
The only use case I see where you would call the `CallbackController` from the application with a POST request is for a login form submission, right?

In that case, you can certainly get a Play CSRF token, put it in the form and check it on the CallbackController using a filter or overriding this class as a new controller to add the `@RequireCSRFCheck` annotation.

I don't think there is anything special in that case. You should test to get a better insight.
