### ISSUE TITLE
JSON support broken: Secure(parser = parse.json)

### ISSUE THREAD

**Issue by henrymana** [pac4j/play-pac4j#161]
version 2.6.0 breaks json support

This used to parse the request body into a JsObject

`
Secure(parser = parse.json, clients = null, authorizers = null, multiProfile = false)(action)
`

It now fails with a class cast exception (unable to cast JsObject to AnyContent)

Issue around line 80:
https://github.com/pac4j/play-pac4j/blob/master/src/main/scala/org/pac4j/play/scala/Security.scala#L80

I rolled back to version 2.5.2 which works and just wanted to report the issue.

**Comment by leleuj** [comment]
Indeed, we were too naive in this direct cast, we should check the type of request first. We'll fix that in a 2.6.1 release.

Would you mind submitting a patch for this?

**Comment by henrymana** [comment]
Cool, I can look into it but won't be able until late December.

**Comment by leleuj** [comment]
No problem. Thanks

**Comment by KarelCemus** [comment]
+1 for this major issue. It does not affects only JSON support. It dies [here](https://github.com/pac4j/play-pac4j/blob/master/src/main/scala/org/pac4j/play/scala/Security.scala#L80)

```
Execution exception[[ClassCastException: play.api.mvc.MultipartFormData cannot be cast to play.api.mvc.AnyContent]]
```

**Comment by leleuj** [comment]
Yes, sure, your contribution will be highly appreciated.

**Comment by KarelCemus** [comment]
I'm just looking at it but I do not see any other solution than pattern match on request body which is kinda ugly solution. The good thing is that AnyContent is sealed trait but still I'd prefer some easier solution. Thoughts?

**Comment by KarelCemus** [comment]
I've read the discussion about #142 and I'm not sure I follow. I don't understand why do you convert scala requests to Java, personally, I don't like this approach. Isn't there other easier solution on parallel `Security` implementation? It might be better when somebody more insightful take a look at this fix.

**Comment by leleuj** [comment]
We need to the check the request type to avoid impossible cast: can we just test the request type and have two logics (the old one and the current one)? Or is this what you propose with pattern matching?

To your second question: pac4j is written in Java as well as the heart of play-pac4j, the Scala Security and SecurityFilter components thus need to convert Scala request to Java.

**Comment by KarelCemus** [comment]
Basically yes, I do. Look [here](https://github.com/playframework/playframework/blob/d96d42e4baa2261d0e0a9c36518f6921e247e402/framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala#L33). All these subtypes of AnyContent it must support, basically, if you are not familiar with Scala, in this example, you can see the pattern matching like switch with `instanceOf`. So yes, we could check for each type and then convert it accordingly.

Oh, I see.

**Comment by leleuj** [comment]
I don't think we are interested in all subtypes supported. Either it's an `AnyContentAsFormUrlEncoded` and we have some custom logic to get the data and build a new `PlayWebContext` or we just create a `PlayWebContext` from the request.

If you're comfortable with this change, can you submit a PR ? Thanks.

**Comment by leleuj** [comment]
@henrymana @KarelCemus  : can you confirm everything is ok for you with version 2.6.1-SNAPSHOT ?

I'll do a release very soon...

**Comment by KarelCemus** [comment]
I think so, I've tested the scenario which failed before, and it works now. But I have not tested CSRF protection.

**Comment by leleuj** [comment]
OK. I'll check CSRF...

**Comment by leleuj** [comment]
The version 2.6.1 has been released.

**Comment by KarelCemus** [comment]
Thanks for the release, however, it seems like you have forgotten to publish it into [Maven repository](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.pac4j%22%20AND%20a%3A%22play-pac4j%22).

**Comment by leleuj** [comment]
You're completely right, I just did it. It should really be available within a few hours this time.
