### ISSUE TITLE
Overwrite DeadboltHandler#getPermissionsForRole to @RoleBasedPermissions works

### ISSUE THREAD

**Issue by leleuj** [pac4j/play-pac4j#163]
@mikefarias @heat @millross

**Comment by leleuj** [comment]
The first step is to return all the permissions of the user profile.

**Comment by heat** [comment]
Ok. It was implemented. 
#165 
But has a concept mistaken. 
Debugging it `ConstraintLogic#roleBasedPermissions` I found that the list of permisions returned from `getPermissionsForRole` are checked with  current `Subject#getPermissions`.

So it's always authorized. 
I'm  working in a `delegate` approach for correct solution.

**Comment by leleuj** [comment]
Thanks for testing it thoroughly. This "role based permissions" concept is not fully clear to me yet. Waiting for your proposal...

**Comment by heat** [comment]
The anotation `@RoleBasedPermissions` will check all permissions from a given Role to current Subject Permissions.
For instance, 
A Role ADMIN has ['email.search', 'attach.open' ] permissions. We can't have a easy Pattern to check all permissions. Using `@RoleBasedPermissions` will check all that permissions and going to authorize even if Subject isn't in ADMIN role but has the permissions.
