### ISSUE TITLE
Documentation is pretty bad

### ISSUE THREAD

**Issue by bharal** [pac4j/play-pac4j#171]
Hi

where do i find what imports to use for the SecurityModule you've put in the documentation? Can someone just add it in please?

**Comment by leleuj** [comment]
There are demos where the pac4j capabilities are demonstrated, especially: https://github.com/pac4j/play-pac4j-java-demo/blob/master/app/modules/SecurityModule.java and https://github.com/pac4j/play-pac4j-scala-demo/blob/master/app/modules/SecurityModule.scala

And feel free to submit a pull request to improve the documentation.

**Comment by millross** [comment]
Also note that the demo is - I think - referenced in the documentation.
