### ISSUE TITLE
Please put in the imports in the documentation

### ISSUE THREAD

**Issue by bharal** [pac4j/play-pac4j#172]
Hi,

I'm requesting that you put the imports in the code samples in the documentation. I don't know how to make pac4j work, and to use the sample SecurityModule I need the import statements

thanks

**Comment by leleuj** [comment]
This is something you can easily contribute thanks to our previous discussion: https://github.com/pac4j/play-pac4j/issues/171

**Comment by leleuj** [comment]
Closed by #https://github.com/pac4j/play-pac4j/pull/175
