### ISSUE TITLE
auto login after register

### ISSUE THREAD

**Issue by mmoulou** [pac4j/play-pac4j#174]
Hello,

Is there anyway (using pac4j) to autologin new user after subscription?

Thanks

**Comment by leleuj** [comment]
It's better to ask your question on the mailing list for others to read the discussion: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users

To answer your question, you cannot do that automatically. You need to do it manually.
For example, you can save a created profile in the security context using the `ProfileManager` (beware that the `AuthorizationGenerator`s need to be called explicitly in that case).
