### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by nik** [pac4j/play-pac4j#176]
I just want to verify that registration doesn't come out of the box and that I'm not missing something? I saw in a random pac4j google group topic that you guys were planning on adding registration for 1.9, and it's already 3.0 but I don't see any documentation on it?

**Comment by millross** [comment]
AFAIK we haven't got to it yet. We're not a very big team, and I believe we all have day jobs, so there's only so much that's going to get done. 

Also we've not yet released 2.0 of pac4j, so your numbers are a little out.

**Comment by nik** [comment]
Oh I meant the play-pac4j version (3.0.0-RC2). But that makes sense, thanks a lot for the quick response

**Comment by leleuj** [comment]
It's fairly recent, but it has been developed in pac4j v2.0 for LDAP, SQL and MongoDB. See: http://www.pac4j.org/docs/authenticators/ldap.html, http://www.pac4j.org/docs/authenticators/sql.html and http://www.pac4j.org/docs/authenticators/mongodb.html.

The `XAuthenticator` classes are now replaced by the `XProfileService` components which know how to validate credentials but also how to create, update and remove users in their specific datastore.

**Comment by millross** [comment]
Ah - now I understand. However, I'm assuming we'll build some registration stuff into core for commonality. Also the implementation versions such as vertx-pac4j (my baby) and play-pac4j may jump forward ahead of core since we switched to semantic versioning so any API break forces a major version jump - a major version may not mean "lots of new functionality" . vertx-pac4j is on 3.0.0-SNAPSHOT for that reason.

**Comment by millross** [comment]
I didn't know we already had something already there - nice one Jérôme :)

**Comment by nik** [comment]
Awesome @leleuj , I didn't realize Mongo supported registering as well but I now see the first sentence on that page which I clearly missed `pac4j allows you to validate username/password and create, update and delete users on a MongoDB database`

Will be playing with this. Thanks @millross , @leleuj ! Fastest response times I've ever dealt with

**Comment by nik** [comment]
@leleuj  / @millross hey guys..so i'm back with a question. after mucking around a bit, i've got the mongo setup working with registering and persisting users with this code:

```
 public Result Signup() throws HttpAction {
    final PlayWebContext context = new PlayWebContext(ctx(), playSessionStore);
    final DirectFormClient directFormClient = (DirectFormClient) config.getClients().findClient("DirectFormClient");
    MongoProfile mongoProfile = new MongoProfile();
    mongoProfile.setId("test@test.com");
    mongoProfile.addAttribute("username", "johnny");
    ((MongoProfileService)directFormClient.getAuthenticator()).create(mongoProfile, "test");
    return ok();
  }
```

I'm hoping to make this app do stateless auth with JWTs (it's a simple REST api). My login looks something like this (which isn't working) .. 

```
public Result Login() throws CredentialsException, HttpAction {
    final PlayWebContext context = new PlayWebContext(ctx(), playSessionStore);
    UsernamePasswordCredentials credentials = new UsernamePasswordCredentials("johnny", "test", "DirectFormClient");
    final DirectFormClient client = (DirectFormClient) config.getClients().findClient("DirectFormClient");
    client.getAuthenticator().validate(credentials, context);
    client.getProfileCreator().create(credentials, context);
    // putting a breakpoint in here and using ProfileManager to get profiles from the context isn't 
    // returning me anything
    return ok();
  }
```

I guess my two main questions are: first off, am I so far on the right track in terms of how this lib should be used? Should I be using `DirectFormClient`? I read through the docs, but I don't see many examples with the thing that I'm trying to accomplish. 

Second question: based on the play-pac java demo example, I see a `FormClient` being used to login, and then you properly generate a JWT based on a created Profile from the login based on what I understand. There is a slight difference with my code because it's not relying on sessions, and need to auth on every request. How would you recommend I setup the login method to do this? The place where I put the breakpoint (in the login method) after calling ` client.getProfileCreator().create(credentials, context);` doesn't populate the `ProfileManager` for some reason. 

Would love to get this working, and even make a pull request for a tutorial in the docs once I get it going the right way with Mongo.

**Comment by leleuj** [comment]
- First question: you should never directly manipulate the `DirectFormClient`: it must be defined in the `SecurityModule`,  then used on some URL with the `Secure` annotation: `@Secure(clients = "DirectFormClient")`. This will perform the authentication based on the form parameters.
For a direct client, the authentication will only be available for the current HTTP request. Thus, you can get the user profile using the `ProfileManager` and generate the JWT.

- Second question: the `FormClient` performs an authentication which remains in the session while the `DirectFormClient` only performs the authentication for the current HTTP request. For web services, use the `DirectFormClient`.

Please read: http://www.pac4j.org/1.9.x/docs/clients.html#direct-vs-indirect-clients

**Comment by nik** [comment]
@leleuj Thanks for the response. So as far as I am understanding from the library, I thought that you would use `@Secure(clients = "DirectFormClient")` for a URL that needs to be authed. So in my case I wouldn't lock down the `Signup` or `Login` endpoint because you're still not authed at that point? 

In my JWT case, I thought that I should use `directformclient` directly to sign up and login with a username/password, and then use `@Secure(clients = "ParameterClient")` to actually do the authing for each request for the secure endpoints?

**Comment by leleuj** [comment]
As your app is mostly a REST api, your solution makes sense: use a `DirectFormClient` just for login and generate a JWT you return for future calls.

**Comment by nik** [comment]
Thanks, so far it's working. The other thing I realized reading through the source code is that starting in version 2, the library reads attributes through deserialization. This seems to prevent me from having attributes live on my mongo collection and kind of just packs everything into one -- `serializedProfile`. Why was this done this way? If I want to query my collections by attributes, I can't seem to properly do so because everything is packed into one attr. Do you suggest having pac4j use their own `Account` collection for auth and linking to my own internal user model called `User` or something, and actually use this model for querying by attributes?

**Comment by leleuj** [comment]
You have the two options in fact (using the `serializedprofile` attribute from pac4j or your own custom attributes). You just need to define the list of custom attributes via the constructor or the `setAttributes` setter.
See: http://www.pac4j.org/docs/authenticators/mongodb.html

**Comment by nik** [comment]
Okay got it. It's just that it's deprecated so I figured it's not really meant to be used at this point. Also -- just wanted to note that when serializing an `ObjectId` type doesn't work well. I had to do `.toString()` on it when serializing to properly deserialize it. Not sure why.

**Comment by leleuj** [comment]
You're right: marking `deprecated` the old attributes support was too much: I'll revert that before 2.0 final release.

About the issue you encountered with the `ObjectId`, do you have some example with which I could reproduce it?

**Comment by nik** [comment]
I don't have any out of the box code, but basically if I do this:

```
MongoProfile mongoProfile = new MongoProfile();
    mongoProfile.setId(userViewModel.getEmail());
    mongoProfile.addAttribute("personId", new ObjectId());
    mongoProfile.addAttribute("someAttr", false);
    mongoProfile.setLinkedId(person.id.toString());
```

then run 
` ((MongoProfileService) directFormClient.getAuthenticator()).create(mongoProfile, webContext.getRequestParameter("password"));`

to actually persist the data, and then login & fetch the profile with:

```
  @Secure(clients = "ParameterClient")
  public Result secureEndpoint() {
      PlayWebContext webContext = new PlayWebContext(ctx(), playSessionStore);
      final ProfileManager<MongoProfile> profileManager = new ProfileManager<>(webContext);
      MongoProfile profile = profileManager.get(false).get();
      return ok(Json.toJson(profile));
  }

```

in a debugging session, doing `profile.getAttribute("personId")` returns some weirdness that is not an `ObjectId` (as far as i remember something like `"size = 0"`) .. I tried playing with it a bunch and even creating my own `Converter` to BSON and stepping through the code to see where the attribute gets muddled, but I eventually got super confused and gave up.

**Comment by leleuj** [comment]
It seems very strange as the `ObjectId` class is `Serializable`. I opened: https://github.com/pac4j/pac4j/issues/891 for tracking.
