### ISSUE TITLE
Issue while creating single authentication client

### ISSUE THREAD

**Issue by studentitm** [pac4j/play-pac4j#178]
I was trying to integrate CAS client in play-pac4j.
Play version: 2.4.2
play pac4j version: 2.3
I only have CAS server so i wanted to authenticate with only it, instead of other methods too.
But the example in demo app uses all the clients(CAS, FACEBOOK, etc.)
My code in SecurityModule:-
val casClient = new CasClient("https://abc.com/login")
    casClient.setLogoutHandler(new PlayCacheLogoutHandler())
    casClient.setCasProtocol(CasProtocol.CAS20)
 val clientL = new Clients(baseUrl,casClient)
But i am getting following errors:-

Multiple markers at this line:
	- overloaded method constructor Clients with alternatives: (x$1: 
	 org.pac4j.core.client.Client[_ <: org.pac4j.core.credentials.Credentials, _ <: 
	 org.pac4j.core.profile.CommonProfile]*)org.pac4j.core.client.Clients <and> (x$1: 
	 String,x$2: org.pac4j.core.client.Client[_ <: org.pac4j.core.credentials.Credentials, _ 
	 <: org.pac4j.core.profile.CommonProfile])org.pac4j.core.client.Clients <and> (x$1: 
	 String,x$2: org.pac4j.core.client.Client[_ <: org.pac4j.core.credentials.Credentials, _ 
	 <: org.pac4j.core.profile.CommonProfile]*)org.pac4j.core.client.Clients <and> (x$1: 
	 String,x$2: java.util.List[org.pac4j.core.client.Client[_ <: 
	 org.pac4j.core.credentials.Credentials, _ <: 
	 org.pac4j.core.profile.CommonProfile]])org.pac4j.core.client.Clients cannot be 
	 applied to (String, org.pac4j.cas.client.CasClient)
	- overloaded method constructor Clients with alternatives: (x$1: 
	 org.pac4j.core.client.Client[_ <: org.pac4j.core.credentials.Credentials, _ <: 
	 org.pac4j.core.profile.CommonProfile]*)org.pac4j.core.client.Clients <and> (x$1: 
	 String,x$2: org.pac4j.core.client.Client[_ <: org.pac4j.core.credentials.Credentials, _ 
	 <: org.pac4j.core.profile.CommonProfile])org.pac4j.core.client.Clients <and> (x$1: 
	 String,x$2: org.pac4j.core.client.Client[_ <: org.pac4j.core.credentials.Credentials, _ 
	 <: org.pac4j.core.profile.CommonProfile]*)org.pac4j.core.client.Clients <and> (x$1: 
	 String,x$2: java.util.List[org.pac4j.core.client.Client[_ <: 
	 org.pac4j.core.credentials.Credentials, _ <: 
	 org.pac4j.core.profile.CommonProfile]])org.pac4j.core.client.Clients cannot be 
	 applied to (String, org.pac4j.cas.client.CasClient)

How can i work without having to define other clients too?

**Comment by leleuj** [comment]
This stack trace is hard to read, can you re-format it? For sure, you can have only one client, like the `CasClient`.
