### ISSUE TITLE
Need better Guice examples

### ISSUE THREAD

**Issue by gmethvin** [pac4j/play-pac4j#180]
In your README, you demonstrate creating a Guice `AbstractModule`, but you seem to be doing all the initialization in the module. This is problematic because [modules should be fast and side effect free](https://github.com/google/guice/wiki/ModulesShouldBeFastAndSideEffectFree) and also because it's very difficult to extend. Generally a Guice module should avoid creating actual instances of things in the `configure()` method and just declare bindings to classes, providers, and simple constant values.

I would suggest using providers or [@Provides methods](https://github.com/google/guice/wiki/ProvidesMethods) for creating the various components. This way you're only doing initialization when the injector is created, and the example is easy to extend with additional dependency, for example to look up something in a database.

(I am not a pac4j user but I'm a Play contributor and occasionally help Play users who use pac4j.)

**Comment by leleuj** [comment]
You're completely right. We have two demos to demonstrate this library: https://github.com/pac4j/play-pac4j-java-demo and https://github.com/pac4j/play-pac4j-scala-demo

Would you mind submitting pull requests to upgrade the demos in that way? Thanks

**Comment by leleuj** [comment]
Any update on this?

**Comment by bropoCorpd** [comment]
I agree with gmethvin, the demo is too simple, and doesn't show how to PROPERLY use pac4j, with subscription and how to save user profiles in database for authorization generators.
I indeed used a provider to set the different authorizers and generators

**Comment by leleuj** [comment]
The demo already proposes many authentication systems. But I'll welcome any pull request for improvement.

**Comment by vidma** [comment]
+1 👍 . just ran into an issue where I had to inject some mysql DAO for my custom authenticator, and it was impossible to do within `configure()`. 

The docs of `AbstractModule` and `pac4j-play(*)` were quite miserable, so I had wasted a few hours trying to work around this.
Apparently `@Provides` solved it easily...

here's some sample code for Scala:

```scala
class SecurityModule(environment: Environment, conf: Configuration) extends AbstractModule {
  override def configure(): Unit = {
    bind(classOf[PlaySessionStore]).to(classOf[PlayCacheSessionStore])

    val baseUrl: String = getBaseUrl(conf)
    // callback
    val callbackController = new CallbackController()
    callbackController.setDefaultUrl(baseUrl + "?defaulturlafterlogout")
    bind(classOf[CallbackController]).toInstance(callbackController)

    // logout
    val logoutController = new LogoutController()
    logoutController.setDefaultUrl(baseUrl)
    bind(classOf[LogoutController]).toInstance(logoutController)
  }

  @Provides
  def providePac4JConfig(
                         userDAO: UserDAO, // the thing to inject, impossible within configure()
                         conf: Configuration) : Config = {
    lazy val pwdStore = new MyOwnMysqlPasswordStore(conf, userDAO)
    val baseUrl: String = getBaseUrl(conf)

    // modify here to any other Auth method supported by pac4j
    val mysqlAuth = new MyOwnSimpleUserPassAuthenticator(pwdStore.validateCredentials)
    val enabledClients = Seq(new FormClient(baseUrl + "/loginForm", mysqlAuth))
    val clients = new Clients(baseUrl + "/callback", enabledClients: _*)
    val config = new Config(clients)
    config.addAuthorizer("admin", new RequireAnyRoleAuthorizer[Nothing](profiles.ROLE_ADMIN))
    config.setHttpActionAdapter(new DefaultHttpActionAdapter())
    config
  }

  private def getBaseUrl(conf: Configuration) = {
    conf.getString("pac4j.baseUrl").getOrElse("")
  }
}
```

Cheers!

**Comment by leleuj** [comment]
Your pull requests on the demos and for the README will be more than welcome!

**Comment by leleuj** [comment]
`@Provides` is now used in the `SecurityModule`.
