### ISSUE TITLE
Access Subject or Profile from template

### ISSUE THREAD

**Issue by joantune** [pac4j/play-pac4j#181]
Hi guys!

I think that it's pretty common to be able to require access to either the Subject or the Profile from within a Twirl template.

So I think that a (better ?) method should be found and recorded on the documentation

I struggled a bit with this, but I was able to come up with it inspired on the `subjectPresent` and other Deadbolt helpers 

for that I simply added the following imports to the template where I want to get the Subject:

```
@import be.objectify.deadbolt.java.ViewAccessPoint.Implicits._
@import play.api.Play.current
@import play.mvc.Http
```

And then called

```
@handlerCache.get().getSubject(Http.Context.current())
```
to be able to access Deadbolt's subject.

From my poking around, I gather that there should be a way to inject the PlaySessionStore from the template and use it to retrieve the profile as per the current examples/docs of the Pac4j.

see https://github.com/playframework/twirl/pull/100 on how to do that.

WDYT?

**Comment by leleuj** [comment]
Yes, I agree: the `Profile` (and `Subject`)  should be available by default in the template.

Would you mind submitting a pull request for that (targeting the master branch)?

**Comment by leleuj** [comment]
What's the status on this issue?

**Comment by vidma** [comment]
so the only slightly nasty (or bureaucratic) part is that injecting stuff into template requires injecting the template into the controller.
  I'd guess this would be even weirder with template inclusion/layout...

see https://www.playframework.com/documentation/2.6.x/ScalaTemplateUseCases

example how template DI might work:

template:
```html
@this(securityHelpers: SecurityHelpers)
@(templateParam: Seq[String])

<p>Here is: @templateParam</p>

Roles: @{securityHelpers.getProfile.getRoles}
```

controller:

```scala
class StuffController @Inject()(
      indexTemplate: views.html.stuff.IndexTemplate,
      addTemplate: ...) extends AbstractController(cc) with I18nSupport {
  def index = Action{
      val templateParam = Seq()
      Ok(indexTemplate(templateParam))
  }
 }
```

**Comment by vidma** [comment]
alternatively, maybe making it an implicit at controller level, and requiring an implicit at template  would make it kinda bearable...

https://github.com/playframework/twirl/issues/47

**Comment by joantune** [comment]
Sorry guys, I haven't had the time for this. @vidma  I would check how Deadbolt did it (not that it's the best way, but we can get inspiration from their solution), I think it's the latter option of the implicits that they use (?)

**Comment by vidma** [comment]
however, the nasty part is the amount of boilerplate needed - inject stuff all over around.

`inject EVERY view into controller` -> 
`inject layout into EVERY view` -> 
`inject securityHelpers in layout`

**Comment by leleuj** [comment]
I'm in line to make the profile(s) easily accessible in templates, but the gain is not really clear here.  A pull request would help.

What about a `BaseController` in Java like the `Security` trait in Scala with a `getProfiles()` method from which the profiles could be passed to the view?

**Comment by vidma** [comment]
so there's these different approaches possible:
1. where controller explicitly passes the profiles (so each controller must be aware of auth lib used), example below
2. profiles or anything else are injected into the template without controller involvement, e.g. https://github.com/pac4j/play-pac4j/issues/181#issuecomment-334476446
3. possibly bad: passed somehow magically (global state, requestHeader subclass, whatever) 

all are quite boilerplate requiring.


what you mentioned is the first approach:
> What about a BaseController in Java like the Security trait in Scala with a getProfiles() method from which the profiles could be passed to the view?

a possibly cleaner alternative would be something like this, not requiring to extend pac4jBaseController which might be quite limiting:

```scala
class StuffController @Inject()(
      implicit val profilesHelper: Pac4jProfileHelper // injected and marked implicit
  ) extends AbstractController(cc) with I18nSupport {

  def index = Action{
      Ok(views.html.index()) // implicit Pac4jProfileHelper
  }
}
```

deadbolt-scala suggests using approach 2.

**Comment by leleuj** [comment]
Indeed, changing the controller would create a tight coupling. I like your solution with the implicit `Pac4jProfileHelper`. I'm not sure how the `Pac4jProfileHelper` would get access to the current `requestHeader` though (I guess the `PlaySessionStore` would be injected).

Let's open two PRs: one in this current library, the other one in a demo to see the change in action...

**Comment by leleuj** [comment]
I plan to release play-pac4j v4.0.0 soon, it's been long-awaited, we'll add that in the next minor version (4.1)...

**Comment by vidma** [comment]
> I'm not sure how the Pac4jProfileHelper would get access to the current requestHeader though.

template: 
`@(params:...)(implicit requestHeader: RequestHeader)`

controller:

```scala
// injected indexView, this template gets all stuff via injection too.

def index = Action { implicit request =>
      Ok(indexView()) // passed implicit request
  }
```

>  (I guess the PlaySessionStore would be injected

yes

**Comment by leleuj** [comment]
OK. We still need to change the template with the `implicit requestHeader`, but the `Pac4jProfileHelper` is just at the controller level (instead of all actions).

Sounds good to me. Looking forward to your pull requests.

**Comment by leleuj** [comment]
Sure. Go ahead and I'll review them.

**Comment by tuxBurner** [comment]
Example is here: https://github.com/tuxBurner/play-pac4j-scala-demo/tree/issue/%23181

**Comment by tuxBurner** [comment]
Hi @leleuj i added the documentation :)
