### ISSUE TITLE
 Unable to implement play-pac4j 3.0.0 on playframework 2.6.1 (version 4.0.0 missing) 

### ISSUE THREAD

**Issue by balyszyn** [pac4j/play-pac4j#183]
Please, make change in pac4j-play for using Async Cache Api (play 2.6 ehcache module)

**Comment by leleuj** [comment]
Can you elaborate a little more on this?

@taggiasco : still planning to update the play-pac4j demos with the latest v4.0.0-SNAPSHOT of play-pac4j?

**Comment by taggiasco** [comment]
@leleuj yes I'll do it as soon as I can..

**Comment by kildievr** [comment]
Also 4.0.0 RC not in maven https://mvnrepository.com/artifact/org.pac4j/play-pac4j

**Comment by leleuj** [comment]
As explained in the README (https://github.com/pac4j/play-pac4j#development), snapshots are available in the Sonatype repo: https://oss.sonatype.org/content/repositories/snapshots/org/pac4j/play-pac4j/4.0.0-SNAPSHOT/

**Comment by wwbakker** [comment]
@leleuj  The snapshot version works for us. Could you release it?

**Comment by leleuj** [comment]
Thanks for the feedback. We still need to update the demos and I plan to do more tests on it. Then, I'll do the release.

**Comment by wwbakker** [comment]
👍

**Comment by robinspollak** [comment]
is there currently a way to implement the 4.0.0 snapshot to be used with scala 2.12 and play 2.6?

**Comment by schmielinski** [comment]
I'm using in my project 4.0.0-SNAPSHOT and play 2.6.2 with scala 2.12 and everything works fine.
@leleuj few days ago wrote hot to use it.

**Comment by leleuj** [comment]
We're working on updating the demos to play-pac4j 4.0.0-SNAPSHOT: here is the PR in progress for Scala: https://github.com/pac4j/play-pac4j-scala-demo/pull/42/files It should give you a valuable insight of what to do.

**Comment by rexxx81** [comment]
@leleuj Could you please also provide the PR in progress for the Java demos?

**Comment by leleuj** [comment]
@rexxx81 Here it is: https://github.com/pac4j/play-pac4j-java-demo/pull/44

It was fairly straightforward...

**Comment by rexxx81** [comment]
@leleuj  Thank you for the quick help!
