### ISSUE TITLE
play-pac4j 4.0.0 not found on Maven repo

### ISSUE THREAD

**Issue by EstaWang** [pac4j/play-pac4j#190]
libraryDependencies += "org.pac4j" % "play-pac4j" % "4.0.0"
will result in a 404 not found

**Comment by leleuj** [comment]
play-pac4j v4.0.0 has not been released yet, but I planned to cut an RC1 soon as I have received many inquiries about that.
So the 4.0.0-SNAPSHOT can be found in the Sonatype snapshots repository: https://oss.sonatype.org/content/repositories/snapshots/org/pac4j/play-pac4j/4.0.0-SNAPSHOT/
