### ISSUE TITLE
Getter/Setter with differing types in UserProfile

### ISSUE THREAD

**Issue by bropoCorpd** [pac4j/play-pac4j#192]
a userProfile that extends pac4j's UserProfile, cannot be persisted with the new PojoCodecProvider, from Mongo 3.5. this is due to the fact that when bson tried to serialize/deserialize the POJO, it doesn't find a matching signatures for getter/setter for the field id (and probably for some other fields like Gender/Locale).
the error we get : o**rg.bson.codecs.configuration.CodecConfigurationException: Property 'id' in User, has differing data types: TypeData{type=String} and TypeData{type=Object}]**

this is due to the fact that for the id property of UserProfile, we have a setter that takes in an Object, and a getter that returns a String.

public void setId(final Object id);
public String getId(); 

Jerome proposes to solve this issue by using a sort of defined mapping.

I don't think I have the knowledge to solve this correctly, maybe someone else can look into it.

**Comment by leleuj** [comment]
Yes, for now, I propose a workaround, but this must be fixed in the next major version 3.0.

Let's close this issue to open a new one in the core project: https://github.com/pac4j/pac4j/issues/976
