### ISSUE TITLE
Controller is deprecated and conflicting

### ISSUE THREAD

**Issue by KarelCemus** [pac4j/play-pac4j#196]
Since Play 2.6, `play.api.mvc.Controller` trait has been deprecated. When there are new classes extending [`Security`](https://github.com/pac4j/play-pac4j/blob/ddc5165e480ca053883c89ddb56135dd272e402d/src/main/scala/org/pac4j/play/scala/Security.scala#L31), then they use either deprecated `Controller` or conflict with the new `BaseController` trait.

**Comment by leleuj** [comment]
Yes, it's deprecated. What do you propose?

**Comment by KarelCemus** [comment]
Extend `BaseController` instead. I believe it is suggested migration.

**Comment by leleuj** [comment]
Yes, we can do that. For the `Security` trait, the only thing we really need is the `BodyParsers`, but at the same time, the trait is meant to be used in a controller so I guess it makes sense.

PR: https://github.com/pac4j/play-pac4j/pull/198

@gmethvin : any opinion?
