### ISSUE TITLE
Add OIDCProfile refreshToken for KeyCloak

### ISSUE THREAD

**Issue by henrymana** [pac4j/play-pac4j#202]
It seems there is no way to refresh the token currently. I saw the comments in this conversation and thought I would create a ticket.

https://groups.google.com/forum/#!searchin/pac4j-users/refresh|sort:relevance/pac4j-users/ZhX3LhCX1OQ/KyU1-3w3BgAJ

I can contribute but it'll take me some time. I am creating this issue to start a conversation on what would need to be done.

**Comment by leleuj** [comment]
Yes, this is part of the OpenID Connect protocol, but we haven't implemented yet. I'm sure this is completely feasible.
This will be part of pac4j and thus available to play-pac4j.
We are developing the version 3.0.0 of pac4j untill the end of the Year, so you can certainly get in that version.

Please open the same issue on the pac4j project instead.

**Comment by henrymana** [comment]
Thank you. I'll play with the code and re-open it later on then.

**Comment by sorenvalentinjp** [comment]
Was this issue ever implemented? Did anyone find an elegant way to refresh the tokens in the background?
