### ISSUE TITLE
How to link users login

### ISSUE THREAD

**Issue by marioserty** [pac4j/play-pac4j#204]
First of all thanks for this package, it have been a great experience working with it.

I'm currently developing a web application with OAuth2 where I need to allow users to login with a normal DB account, Facebook account and Google account. Searching, I found that there's no way to link multiple logins with the 'linkedid' attribute, and a I really need to link a user that logged with same email on Facebook and Google. Is there an alternative for that? And also, can the default DB be changed?

Thank you.

**Comment by leleuj** [comment]
Currently, there is no way to do that unless something developed specifically.

There was an issue for that, but I closed it as people tend to request features they don't really need. Reopened: https://github.com/pac4j/pac4j/issues/952

Feel free to submit a contribution.

**Comment by marioserty** [comment]
Thanks for de reply.

What alternatives I can use for doing this link ? I really need to link users login by same email to know wich user has a "premium" account or a "standard" account in my app.
Do you recommend any lib?

**Comment by leleuj** [comment]
I recommend implementing something custom. Save multiple ids in the linkedid attribute for example (separated by commas) and subclass the `DbProfileService` to deal with that (save and load).

**Comment by marioserty** [comment]
Thank you very much, me and my team will try to do that.

**Comment by leleuj** [comment]
Or you could try to contribute to the open issue ;-)
