### ISSUE TITLE
Support Scala 2.11 and Scala 2.12

### ISSUE THREAD

**Issue by KarelCemus** [pac4j/play-pac4j#207]
I wanted to use `play-pac4j 4.0.0` with `Play 2.6.6` and Scala 2.11 but it seems it does not work. It throws the `ClassNotFoundException: org.pac4j.play.scala.Security$class`error.

I browsed the code base and figured out the following:

- this lib links only `_2.12` dependencies and scala plugin for maven then compiles the library only against Scala 2.12
- I wanted to compile it myself for 2.11 but there are some places, e.g., `asScalaBuffer`, which depends on Scala 2.12.

As you are Java dev if I remember correctly, it might be worth noting that Scala 2.11 and Scala 2.12 are not binary compatible.

I it possible to still support Scala 2.11 as Play does or is this support dropped? If so, please highlight this inconsistency at homepage documentation (README).

Thanks.

**Comment by leleuj** [comment]
We use to have Scala 2.10 and Scala 2.11 supports for Play 2.3, but we cleaned things for Play 2.4 and kept Scala 2.11 (and only one library instead of 3). Then, for play-pac4j v4 (and Play 2.6), we switched from Scala 2.11 to Scala 2.12. 
But you're right: there is a Scala 2.11 version for Play 2.6.x.
It was a bit reckless, but as I'm mostly on my own on this library, I'm always reluctant de maintain multiple versions.

Is Scala 2.11 still used that much?

In that case, I think we should create two Maven sub-modules: `play-pac4j_2.11` and `play-pac4j_2.12`, one using Scala 2.11 and the other one using Scala 2.12.
If it's not used that much, we can maybe only create a `4.0.0-scala2.11` version compiled with Scala 2.11 and derived from play-pac4j v4.

What's your recommendation?

**Comment by KarelCemus** [comment]
I am not sure how much is Scala 2.11 used, haven't read any statistics, but it is officially supported by Play 2.6.

I don't know how about Maven but SBT makes maintenance of multiple scala versions pretty simple and can publish into regular Maven repo.

**Comment by leleuj** [comment]
According to Google trends, both Scala versions are still widely used: https://trends.google.com/trends/explore?q=scala%202.11,scala%202.12

**Comment by leleuj** [comment]
I just created a new version 5.0.0-SNAPSHOT with both supports for Scala 2.11 and Scala 2.12.

Would you mind testing the Scala 2.11 support? Thanks

**Comment by KarelCemus** [comment]
Hi, thanks for the support. I tested it and encountered several implementational difficulties. I have prepared a PR to propose some changes, only waiting for #222 to know what code base to use - your or with shared sources.

**Comment by KarelCemus** [comment]
I pushed [the commit into my fork](https://github.com/KarelCemus/play-pac4j/commit/204ee9a4602ebf8d628a8c2f6df1e99f7786e9bb), I'll open the PR later when #222 gets either merged or closed.

I encountered these issues:

- `Secure` enforced `AnyContent`, which makes smooth integration with other actions very difficult (or I'm missing something)
- `Secure` expected `List[P] => Action` instead of just an action, which limits action composition. Instead, I introduced `SecureAction` action builder, which uses `AuthenticatedRequest` containing the identities and does not limit action composition at all.
- `Secure` now only expects any action and does not expose identities. To get them, you have to use `SecureAction`
- To ease injection of dependencies, Play uses `ControllerComponents`. I introduced `SecurityComponents` extending `ControllerComponents` and adding all dependencies required by `Security` trait to reduce the number of dependencies to just one.
- The logic itself is unchanged.

Limitations:

- There are some changes in API, though you propose a version `5.0.x`, which allows some breaking changes, I hope.


What do you think? Could you review my proposition? Thanks

**Comment by leleuj** [comment]
Any valuable help will be always appreciated ;-)

We must try to make upgrades as seamless as possible, but indeed, the version 5.0.0 is the perfect timing for relevant breaking changes.

- Removing `AnyContent`: seems a good idea
- Adding `SecurityComponents`:  also

I'm a bit less convinced by the changes proposed with `Secure` and `SecureAction`, but this must be thought and discussed.

Can you open a PR targeting play-pac4j with your changes? And a PR on one of the demo to demonstrate your proposal? Thanks
