### ISSUE TITLE
Cors issue

### ISSUE THREAD

**Issue by prashanthd** [pac4j/play-pac4j#210]
I have been facing issue with cors for last 5 days. Initial I configured how play framework(2.5v) docs provided but it is not working. Then I have seen your documentation [here](https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/authorization/authorizer/CorsAuthorizer.java). I have followed same but it is not working. Even I have added cors headers in  DbProfileService,ProfileManagerFactoryAware<PlayWebContext> and DefaultHttpActionAdapter.
  I am using deadbolt also. Following are the dependecies I have added
libraryDependencies ++= Seq(
  "org.pac4j" % "play-pac4j" % "3.0.0",
  "org.pac4j" % "pac4j-http" % "2.0.0",
  "org.pac4j" % "pac4j-cas" % "2.0.0",
  "org.pac4j" % "pac4j-saml" % "2.0.0",
  "org.pac4j" % "pac4j-oidc" % "2.0.0" exclude("commons-io", "commons-io"),
  "org.pac4j" % "pac4j-jwt" % "2.0.0" exclude("commons-io", "commons-io"),
  "org.pac4j" % "pac4j-sql" % "2.0.0",
  "org.pac4j" % "pac4j-mongo" % "2.0.0",
  "org.pac4j" % "pac4j-stormpath" % "2.0.0",
  "com.typesafe.play" % "play-cache_2.11" % "2.5.8",
  "commons-io" % "commons-io" % "2.4",
  "be.objectify" %% "deadbolt-java" % "2.5.1"
)

**Comment by prashanthd** [comment]
following routes are configured

GET     /                              						@controllers.Application.index
GET     /loginpac                      				 		@org.pac4j.play.CallbackController.callback()
POST    /loginpac                      						@org.pac4j.play.CallbackController.callback()
GET     /callback                   				 		controllers.CustomCallbackController.callback()
POST    /callback                   				 		controllers.CustomCallbackController.callback()

**Comment by leleuj** [comment]
There is some CORS configuration in the demos (https://github.com/pac4j/play-pac4j-java-demo and https://github.com/pac4j/play-pac4j-scala-demo) that I remember testing it successfully.

And please use the mailing list for questions.
