### ISSUE TITLE
saveRequestedUrl/redirectToOriginallyRequestedUrl not working in Play 2.6.12

### ISSUE THREAD

**Issue by thomhickey** [pac4j/play-pac4j#231]
Hello,

I've got SAML2 authentication working with a Play 2.6.12 app, but the handling of pac4jRequestedUrl to save and then redirect to the originally requested url is not working as intended in pac4j. Here's what I'm seeing:

- log out, clear cookies
- request secured url
- o.p.c.e.DefaultSecurityLogic::saveRequestedUrl is invoked and successfully writes to the session store
- pac4j redirects to the idp
- idp redirects back to the acs route (CallbackController)
--> o.p.c.e.DefaultCallbackLogic::redirectToOriginallyRequestedUrl is invoked but cannot find pac4jRequestedUrl in the session because by now a new session has been created in Play

I'm posting here in hopes someone has seen this and can point me in the right direction. I've traced the code and cannot find where pac4j might be destroying the session. Perhaps Play is? 

I've worked around the problem, but the workaround is horrendously ugly - forcing an added parameter onto RelayState and then fetching it back in the acs route. 

Any help appreciated!

-Thom

**Comment by leleuj** [comment]
Please use the mailing list for your questions. I think you need this setting: https://github.com/pac4j/play-pac4j-java-demo/blob/master/conf/application.conf#L68
