### ISSUE TITLE
A stale requested url is resolved when there is no requested url supplied.

### ISSUE THREAD

**Issue by TheChifer** [pac4j/play-pac4j#235]
This is the scenario:
I have an app with 2 clients, a SAML client and a FormClient. The user request a resource secured by the SAML client and gets redirected to the IDP, rather than fulfilling the login process, user enters the url of the FormClient login form - /loginform(NOT a url secured by FormClient). Now there is no requested URL hence the expectation is that user will be redirected to CallbackController.defaultUrl subsequently. But after login user is redirected to the URL requested with SAML client.

 I guess this is caused by Pac4jConstants.REQUESTED_URL  being set on the context and never cleared. 

Play 2.5
play-pac4j 3.1.0

**Comment by leleuj** [comment]
Please use the pac4j-users mailing list for questions: http://www.pac4j.org/mailing-lists.html
