### ISSUE TITLE
pac4j-saml and pac4j-kerberos 3.0.0 have references on Spring Core 5.0.0 causing errors with Play 2.6 Java form helpers

### ISSUE THREAD

**Issue by Mule52** [pac4j/play-pac4j#236]
I am using Play 2.6.15 and Pac4J 3.0.0 (both are the latest at the time of this issue). When I use Play's Java form helpers (https://www.playframework.com/documentation/2.6.x/JavaFormHelpers), I get runtime errors (fatal errors that shut down my server) when using Play's Java form helpers, such as @helper.inputText(userForm("name")). The errors I get are ...

[error] a.a.ActorSystemImpl - Uncaught error from thread [application-akka.actor.default-dispatcher-4]: org/springframework/core/ErrorCoded, shutting down JVM since ‘akka.jvm-exit-on-fatal-error’ is enabled for ActorSystem[application]
java.lang.NoClassDefFoundError: org/springframework/core/ErrorCoded

pac4j-saml and pac4j-kerberos have dependencies on Spring Core 5.0.2.RELEASE. The class ErrorCoded was removed in Spring 5.0.0. If I comment out these two references, I am able to use the Play 2.6 Java form helpers.

A reference to this issue can be found here: https://discuss.lightbend.com/t/play-2-6-pass-new-blank-empty-form-loginform-from-controller-to-login-scala-html/1448.

Thanks.

**Comment by leleuj** [comment]
OK. I see. In fact, we don't have a strong dependency on Spring v5, we could use Spring v4, but I generally update all dependencies to their latest versions when releasing a major version (pac4j v3).

So I think we could try to release a play-pac4j fix version v6.0.1 with an explicit dependency on Spring v4.3.11.

Would you mind submitting a PR for that? Thanks

**Comment by leleuj** [comment]
I have been able to reproduce the issue, I will work on a fix...

**Comment by leleuj** [comment]
I haven't been able to find a solution at the play-pac4j library level. Just use the `exclude` keyword in the `build.sbt` file: https://github.com/pac4j/play-pac4j-java-demo/commit/b6d9a252c1df8c11e4aab24a8ef21b41d0220b46
