### ISSUE TITLE
PlayWebContext incorrectly sets port for requests coming from load balancer

### ISSUE THREAD

**Issue by suhinini** [pac4j/play-pac4j#237]
PlayWebContext incorrectly uses `80` as a default port ignoring `request.secure()`: https://github.com/pac4j/play-pac4j/blob/master/shared/src/main/java/org/pac4j/play/PlayWebContext.java#L181

This is causing problems when library is used in apps that are working from behind load balancers or reverse proxies and security and port of the call is defined by `Forwarded` headers. In such scenario `request.secure()` will return `true`, while code in question will claim port is 80. This causes problems in DefaultUrlResolver of pac4j's core library:
1. `ContextHelper.isHttps(context)` will return `true` as it relies on `request.secure()` that's filled by Play with correct values from `Forwarded` headers.
1. `context.getServerPort()` will return `80` as it does not take `request.secure()` or `X-Forwarded-Port` into account.

Resulting urls look like `https://something.org:80` and this causes obvious problems.

Thanks

**Comment by leleuj** [comment]
Thanks for reporting. Would you mind submitting a PR to fix that (on both the master and 6.0.x branches)? Thanks

**Comment by suhinini** [comment]
Sure. Let's try with master first.
