### ISSUE TITLE
renewsession is not implemented to avoid session fixation issue

### ISSUE THREAD

**Issue by sasankad** [pac4j/play-pac4j#247]
Current implementation of PlayCacheSessionStore returns false on renewSession() method. We should have proper session renewal to avoid session fixation

**Comment by leleuj** [comment]
Feel free to submit a PR for that. Thanks

**Comment by TheChifer** [comment]
I have the same issue. Session fixation is getting flagged as a high risk issue in pen testing.

My attempt was to extend CallbackController(MyCallbackController) and PlayCacheSessionStore(MyPlaySessionStore)

In MyCallbaclController when calling defaultCallbackLogic.perform(...) passed inputRenewSession=true. This causes callbacklogic to initiate session renewal.

The problem I had with PlayCacheSessionStore is that it uses key as SessionID$DataKey to store data in the 'store', hence when I get the oldSessionId I have no way of retrieving all data associated with that oldSessionId. What I did was to use a different structure in the store. It uses sessionId as the key and a HashMap to store store DataKey, value pairs

```
@Override
public void set(final PlayWebContext context, final String key, final Object value) {
	final String sessionId = getOrCreateSessionId(context);
	HashMap<String, Object> values = (HashMap<String, Object>) getStore().get(sessionId);
	if (getStore().get(sessionId) == null) {
		values = new HashMap<String, Object>();
		getStore().set(sessionId, values);
	}
	values.put(key, value);
}
```

```
@Override
public Object get(final PlayWebContext context, final String key) {
	final String sessionId = getOrCreateSessionId(context);
	HashMap<String, Object> values = (HashMap<String, Object>) getStore().get(sessionId);
	if (values != null) {
		return values.get(key);
	}
	return null;
}
```

Once the store is setup like this renewal is trivial

```
@Override
public boolean renewSession(final PlayWebContext context) {
	final String oldSessionId = this.getOrCreateSessionId(context);
	HashMap<String, Object> storeData = getAll(context);
	remove(context);
	final Session session = context.getJavaSession();
	session.remove(Pac4jConstants.SESSION_ID);
	final String newSessionId = this.getOrCreateSessionId(context);
	if (storeData != null) {
		setAll(context, storeData); // utility method to set a the map back.
	}
	Logger.debug("Renewing session: {} -> {}", oldSessionId, newSessionId);
	return true;
}

```

In initial testing solution works well for an custom  user/password Indirect client and a SAML2Client.

@leleuj is this as valid approach?

**Comment by leleuj** [comment]
Before we dive into the technical details of a mitigation solution, I'd like you to describe how a session fixation attack is possible with Play framework. Thanks

**Comment by sasankad** [comment]
owasp has described how to test for session fixation. Simply put, if the session cookie is not renewed after authentication you have a session fixation vulnerability. 

https://www.owasp.org/index.php/Testing_for_Session_Fixation_(OTG-SESS-003)

as described in https://www.owasp.org/index.php/Session_fixation

• Session ID in a cookie:

o Client-side script

Most browsers support the execution of client-side scripting. In this case, the aggressor could use attacks of code injection as the XSS (Cross-site scripting) attack to insert a malicious code in the hyperlink sent to the victim and fix a Session ID in its cookie. Using the function document.cookie, the browser which executes the command becomes capable of fixing values inside of the cookie that it will use to keep a session between the client and the Web Application.

o <META> tag

<META> tag also is considered a code injection attack, however, different from the XSS attack where undesirable scripts can be disabled, or the execution can be denied. The attack using this method becomes much more efficient because it's impossible to disable the processing of these tags in the browsers.

o HTTP header response

This method explores the server response to fix the Session ID in the victim's browser. Including the parameter Set-Cookie in the HTTP header response, the attacker is able to insert the value of Session ID in the cookie and sends it to the victim's browser.

**Comment by leleuj** [comment]
@sasankad I was just expecting some concrete example in the Play framework and pac4j environment, but anyway, let's get this working.

@TheChifer Your analysis is right: the way data are currently stored in the cache does not allow to retrieve all the attributes when we want to change the session id and repopulate all the attributes in the store.
Your solution is the one I think. Can you submit a PR for that? Thanks.
It's a runtime breaking change, it'll go in the version 7.0.0.
