### ISSUE TITLE
Pac4jHandler not support DirectClient

### ISSUE THREAD

**Issue by ihostage** [pac4j/play-pac4j#249]
I try to integrate Lagom, Play-Pac4j, and Deadbolt. Sources in this repo https://github.com/ihostage/lagom-pac4j-deadbolt
But I got a problem.
Case:
## Create Hello World project from maven archetype [commit](https://github.com/ihostage/lagom-pac4j-deadbolt/commit/ebb5d02300e71c80ef9ae1175f3d74415ae7e8a9)

https://www.lagomframework.com/documentation/1.4.x/java/GettingStartedMaven.html
Run services by command:
```bash
$ ./mvnw lagom:runAll
```
Check hello service:
```bash
$ curl http://localhost:9000/api/hello/Alice
Hello, Alice!%
```
## Add Pac4j and Deadbolt [commit](https://github.com/ihostage/lagom-pac4j-deadbolt/commit/81498621fe38faf9d841780f4bffae1e29f46138)
Following the next instructions:
[1) Add the required dependencies (play-pac4j + pac4j-* libraries)](https://github.com/pac4j/play-pac4j#1-add-the-required-dependencies-play-pac4j--pac4j--libraries)
[2) Define the configuration (Config + Client + Authorizer + PlaySessionStore)](https://github.com/pac4j/play-pac4j#2-define-the-configuration-config--client--authorizer--playsessionstore)
[3c) Working with Deadbolt](https://github.com/pac4j/play-pac4j#3c-working-with-deadbolt)
[Deadbolt Authorized routes](https://deadbolt-java.readme.io/docs/authorized-routes)

I wrote very simple `HeaderClient` (`DirectClient`) and added Pac4j and Deadbolt.

Check hello service without auth header:
```bash
$ curl http://localhost:9000/api/hello/Alice
authentication required%
```
Success 😄 
Check hello service with auth header:
```bash
$ curl -H "Authorization: Alice" http://localhost:9000/api/hello/Alice
authentication required%
```
Failed 😞 

## Customize Pac4jHandler [commit](https://github.com/ihostage/lagom-pac4j-deadbolt/commit/a26f675f89f97972321585f7e7697d6d4ff92648)
Add hack code for DirectClient in function `beforeAuthCheck`:
```java
} else if (isNotEmpty(currentClients) && currentClients.get(0) instanceof DirectClient) {
    Credentials credentials = currentClients.get(0).getCredentials(playWebContext);
    if (credentials != null) {
        playWebContext.setRequestAttribute(Pac4jConstants.USER_PROFILES, credentials.getUserProfile());
        // playSessionStore.set(playWebContext, Pac4jConstants.USER_PROFILES, credentials.getUserProfile());
        return Optional.empty();
    }
    logger.debug("unauthorized");
    action = unauthorized(playWebContext, currentClients);
}
```
Check hello service without auth header:
```bash
$ curl http://localhost:9000/api/hello/Alice
authentication required%
```
Success 😄 
Check hello service with auth header:
```bash
$ curl -H "Authorization: Alice" http://localhost:9000/api/hello/Alice
Hello, Alice!%
```
Success 😄 

## Summury

1. I'm not sure that I used the right way to fix a problem of `DirectClient`. Maybe you suggest me the idiomatic way?
2. I'm not understand, why need `PlayCookieSessionStore`, because I not see cookies in the server response. Maybe it's even good for stateless microservice and authentication by `DirectClient`.

**Comment by ihostage** [comment]
Hi, @leleuj!
Even after fix `Pac4jHandler`, I can't retrieve CommonProfile in my Lagom service 😞 
For doing that need great refactoring (including Deadbolt). 😞 
I tried to use the recommended [Lagom service call composition](https://www.lagomframework.com/documentation/1.4.x/java/ServiceImplementation.html#Service-call-composition) for authentication and authorization. In this [commit](https://github.com/ihostage/lagom-pac4j-deadbolt/commit/a858753286ba4acba8e3f0bc9fde0a967896b9ac), I wrote draft authorization service of greeting using `pac4j-jwt`.
It seems the time has come to create `lagom-pac4j` 😂

**Comment by leleuj** [comment]
About the `PlaySessionStore`, you have two options in Play. See: https://github.com/pac4j/play-pac4j/wiki/Security-configuration#2-choosing-the-right-playsessionstore

If you want to create a new pac4j implementation, take a look at http://www.pac4j.org/docs/how-to-implement-pac4j-for-a-new-framework.html

**Comment by ihostage** [comment]
> About the `PlaySessionStore`, you have two options in Play. See: https://github.com/pac4j/play-pac4j/wiki/Security-configuration#2-choosing-the-right-playsessionstore

Unfortunately, Lagom hasn't context and sessions. It's a framework for microservices and all requests are stateless. That's the problem about I wrote above. I can use Play filters for changing request before it handled by Lagom. But I can't access to Play Context or Play SessionStore from Lagom Service implementation.

> If you want to create a new pac4j implementation, take a look at http://www.pac4j.org/docs/how-to-implement-pac4j-for-a-new-framework.html

Thanks, I read it earlier 😄 But I am not sure that this will be a full implementation. I think, that Lagom services and Pac4j indirect clients are incompatible. But also with direct clients, there can be restrictions. If you look at my commit, I do not use a `DirectClient`, I use `Authorizer` and `Authenticator` directly.

**Comment by leleuj** [comment]
OK. I see. Sure, the documentation is for a whole security framework, but in your case, you only need the direct clients.
The `SessionStore` does not make much sense in your case, maybe `null` or a `NoOpSessionStore` would be sufficient.
About your commit, this is specific to JWT authentication so I still think you could use direct clients for credentials extraction and profile building.

**Comment by ihostage** [comment]
Thanks, @leleuj !
I forced push [commit](https://github.com/ihostage/lagom-pac4j-deadbolt/commit/bba184252e5f3e37b5e53b7d8e7fc347de36f9c3) where authentication/authorization implemented by `DirectClient` and `Config`. (`HeaderClient` + `JwtAuthenticator` + `KeycloakOidcProfile` + custom `AuthorizationGenerator`).
But two classes `LagomWebContext` and `SecuredService` not enough for a separate library on Pac4j family 😂

**Comment by leleuj** [comment]
I would say three classes with the `Authorizers` one.
I didn't know it but Lagom seems to be a pretty well-known framework (~ 2k stars on github.com). So I think it's worth to create a dedicated library if you are willing to.

I can create the lagom-pac4j repo in the pac4j organization if you are interested...

**Comment by ihostage** [comment]
> I can create the lagom-pac4j repo in the pac4j organization if you are interested...

Of course interested 👍 We planned to create a repo `lagom-pac4j` in our organization [`taymyr`](https://github.com/taymyr), but I think that it will be better if repo will be created in the `pac4j` organization.

**Comment by leleuj** [comment]
Here it is: https://github.com/pac4j/lagom-pac4j

You have no push rights for now: you'll need to make PRs that I can review...

**Comment by ihostage** [comment]
> Here it is: https://github.com/pac4j/lagom-pac4j

It's great 👍 
>You have no push rights for now: you'll need to make PRs that I can review...

Yes, of course. Please, create an initial commit with LICENSE or README, because I can't fork empty repository for creating PR. 😄

**Comment by leleuj** [comment]
Done

**Comment by leleuj** [comment]
Closing. Using lagom-pac4j instead.

**Comment by ihostage** [comment]
@leleuj will not be fixed? Does nobody use `play-pac4j` with `DirectClient`? 😄

**Comment by leleuj** [comment]
Many people use `play-pac4j` with a `DirectClient`, but I doubt that many people do that using Deadbolt also. At least, you're the first one to report the issue...

**Comment by ihostage** [comment]
I am lucky 😂 
If I have free time, I will try to do a pull request to fix this issue.

**Comment by leleuj** [comment]
Great! Let's re-open it then if you are willing to fix it :-)

**Comment by eximius313** [comment]
@ihostage I'm also planning to use Play-Pac4J + Deadbolt, so big thumbs up for this ;)
