### ISSUE TITLE
Session timeout after one hour even when session should be prolonged

### ISSUE THREAD

**Issue by iwanek9ld** [pac4j/play-pac4j#254]
I am not sure if this is bug or my misconception about design but I cannot get play-pac4j correctly working with defaults to PlayCacheSessionStore, ehcache play cache, security filter and indirect client.

Versions:
play - 2.6.20
play-pac4j - 6.1.0
pac4j - 3.3.0

Sessions are expired after 1 hour (default) from creation and expiration time is not prolonged on access to session (subsequent requests of web application user). This is due to:
 - PlayCookieSessionStore sets timeout to 1 hour for each session,
 - PlayCookieSessionStore uses default cache implementation from play which is ehcache,
 - play's ehcache implementation of SyncCacheApi is translating timeouts to calls `setTimeToLive(timeout)` insteads of `setTimeToIdle(timeout)` in ehcache,
 - according to above, session is expired after timeout from creation, not key access.

This is at least confusing to me that defaults leads to such surprising effects, I would normally expect that session is prolonged at next requests to web application so that active user is not logged out in middle of session.

My current workaround is to replace cache implementation used by play-pac4j (SyncCacheApi).

**Comment by leleuj** [comment]
Good catch! I had never noticed. Indeed, I was expecting the `setTimeToIdle(timeout)` method to be called. It feels like a bug in Play: did you try to report it to the Play framework team?

**Comment by iwanek9ld** [comment]
Following your opinion that this is clearly play framework bug, I have created issue: https://github.com/playframework/playframework/issues/8861

**Comment by leleuj** [comment]
OK. Thanks. We'll see what they answer...

**Comment by leleuj** [comment]
@iwanek9ld any update on this?

**Comment by aeismann** [comment]
@leleuj After a lengthy migration from secure social to pac4j, I am facing the same problem now.
```
playPac4jVersion 7.0.1
pac4jVersion 3.6.1
play 2.6.20
```
In the configuration the callback controller is configured with: `setRenewSession(true)`.

Current workaround in our code is to override `renewSession(PlayWebContext context)` in `PlayCacheSessionStore`, where we remove the session from the cache and add it again in each call, to 
prolong the cache time. Up to now no performance issues have been experienced using this procedure.

**Comment by leleuj** [comment]
Indeed, renewing the session for each call is a performance pitfall.

play-pac4j only relies on the APIs provided by Play. The `setTimeToLive` (instead of `setTimeToIdle`) call happens in the `EhCacheApi` component. You should certainly override it.

**Comment by almothafar** [comment]
Any update on this, play 2.7.x and still having the same issue! it is annoying.

**Comment by leleuj** [comment]
To handle this issue, you now have a specific `PlayEhCacheSessionStore` to use instead of the `PlayCacheSessionStore`.
