### ISSUE TITLE
profileManager.get(false) returns Optional.empty

### ISSUE THREAD

**Issue by AlexTo** [pac4j/play-pac4j#259]
Hi
I'm using 
Play 2.7, 
play-pac4j 7.0
HeaderClient and JWT 

I can authorize request or reject unauthorized request properly but only having problem with getting the profile from the request.

![untitled](https://user-images.githubusercontent.com/296212/52956977-bb554b00-33e4-11e9-86b1-981a75b9cf31.png)

The headers in the request does contain "authorization Bearer ....."

![untitled2](https://user-images.githubusercontent.com/296212/52956869-7c26fa00-33e4-11e9-84be-d526f65f3203.png)

Any idea what might go wrong?

Thank you

**Comment by leleuj** [comment]
Please use the mailing list for questions: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users
