### ISSUE TITLE
Password sent in query params to callback

### ISSUE THREAD

**Issue by Synesso** [pac4j/play-pac4j#260]
I've set up HTTP form auth with SQL provider. See my [SecurityModule](https://github.com/0rora/0rora/blob/bd02017ee580c52effca5b6015e586b91a3841ee/app/modules/SecurityModule.scala#L19)

When I log in, there is an HTTP GET made to the callback url with username and password fields in the query string.

`http://localhost:9000/callback?username=admin&password=admin`

I'm new, so most likely doing something wrong. But even if I have misconfigured my app, I don't think this should ever happen.

**Comment by leleuj** [comment]
I guess the method of your form is GET (or nothing) instead of POST. Change that to hide your credentials.
