### ISSUE TITLE
Support for scala 2.13?

### ISSUE THREAD

**Issue by louisjiang** [pac4j/play-pac4j#265]
Support for scala 2.13?

**Comment by leleuj** [comment]
Not yet. Feel free to submit a contribution.

**Comment by louisjiang** [comment]
Dependent on external project deadbolt-2-scala
https://github.com/schaloner/deadbolt-2-scala/issues/50

**Comment by leleuj** [comment]
OK. Let's wait for that then.

**Comment by aeismann** [comment]
FYI: @louisjiang That dependency has moved forward now:
https://github.com/schaloner/deadbolt-2-scala/issues/50

**Comment by pbyrne84** [comment]
Deadbolt scala does not look like it has been properly published for 2.11
https://repo1.maven.org/maven2/be/objectify/deadbolt-scala_2.11/2.7.1/
versus 
https://repo1.maven.org/maven2/be/objectify/deadbolt-scala_2.13/2.7.1/

:(

Things seem to of been moved/renamed internally in deadbolt so it may be worth waiting for play 2.8 support as it looks like it has dropped 2.11 simplifying things.

**Comment by leleuj** [comment]
@pbyrne84 Just to be sure: you suggest to first move to Play 2.8 and then remove Scala 2.11 and add Scala 2.13, right?

**Comment by pbyrne84** [comment]
Sorry for not getting back sooner. Well the move to play 2.8 will remove 2.11 as it is no longer supported. The deadbolt changes would now block you and would require incompatible versions of deadbolts to be running across different Scala versions in your build. That does not sound like fun to me.

There is an issue raised for the missing 2.11 build
https://github.com/schaloner/deadbolt-2-scala/issues/51
I assume it is right place as it mentions 2.7.1

**Comment by mkurz** [comment]
I released deadbolt 2.7.1 for Scala 2.11 now:
https://repo1.maven.org/maven2/be/objectify/deadbolt-scala_2.11/2.7.1/
Seems like a problem occured when released last year.

**Comment by mkurz** [comment]
Oh yes and deadbolt 2.8.0 for Scala 2.12 and 2.13 is released now as well. Have fun!

**Comment by leleuj** [comment]
Thanks

**Comment by leleuj** [comment]
@mkurz Just to be sure: for Play 2.7, I must use Deadbolt 2.7 and for Play 2.8, I must use Deadbolt 2.8, right?

**Comment by mkurz** [comment]
@leleuj Yes, that's correct.

**Comment by mkurz** [comment]
Because from deadbolt 2.7  to deadbolt 2.8 nothing really changed, you may be able to use deadbolt 2.7 with Play 2.8. I think that should work as well given that deadbolt 2.8 is just compiled against Play 2.8 without any changes in its source code. However the safest way is probably to just use deadbolt 2.8.
deadbolt 2.7 and deadbolt 2.8 do not differ in features or anything else, it's just recompiled.

**Comment by leleuj** [comment]
@mkurz Thanks for confirming this.

I was in v2.6.1 and I have compilation issues with v2.7.1. I guess things have changed: is there a migration guide somewhere to help me?

**Comment by mkurz** [comment]
Not really a migration guide, but maybe it helps: https://github.com/schaloner/deadbolt-2-java/issues/89

**Comment by leleuj** [comment]
I saw this doc, but it won't be enough for me.

I have taken a look at the documentation (https://deadbolt-java.readme.io/) and I haven't been able to find the guide for a release after the version 2.6.3: am I missing something?

**Comment by leleuj** [comment]
OK. I see the problem: I'm relying on `Http.Context` which has been replaced by `Http.RequestHeader`. This is something I planned to do in play-pac4j even in Play 2.7, so I will start by that. The upgrade should be straightforward after that.

Thanks for your help.

**Comment by mkurz** [comment]
@leleuj If you need help along the way let me know.

**Comment by leleuj** [comment]
Thanks for proposing. Almost all work was on my side. As soon as I used `RequestHeader` instead of `Http.Context`,  the Deadbolt upgrade became easy.

**Comment by mkurz** [comment]
Great!

**Comment by leleuj** [comment]
I just added the Scala 2.13 support as well.
