### ISSUE TITLE
ShiroAesDataEncrypter generates bad default keys

### ISSUE THREAD

**Issue by jonaskoelker-jypo** [pac4j/play-pac4j#271]
I had a look at https://github.com/pac4j/play-pac4j/blob/master/shared/src/main/java/org/pac4j/play/store/ShiroAesDataEncrypter.java (from commit 8f621bba31d55e1fa3e41dae86244b1a82978964).

It appears to me that the argument-less constructor generates weak keys: the byte array used as an AES key will only ever contain values which are either between 48 and 57 ('0' to '9') or 97 and 102 ('a' to 'f'). This means that extremely large portions of the space of 128-bit keys will never be sampled from. In particular, you sample keys from a space of size 16**16 (= 2**64) instead of one of size 256**16 (= 2**128).

I think it would be better if you generated 16 bytes each chosen uniformly at random.

(If I have misunderstood the code or made bad assumptions, I apologize for wasting your time.)

**Comment by leleuj** [comment]
You're right: there is less possible values with a generated key from the default constructor than if you provide your own key. And the size is small.
It has been designed as an easy way to setup things, but it can be a mistake.

I'm not sure about the solution, maybe we should simply remove this default constructor...

**Comment by jonaskoelker-jypo** [comment]
Removing it would work for me, but it will of course break all code that uses it.

Alternatively, https://docs.oracle.com/javase/8/docs/api/java/security/SecureRandom.html suggests a recipe:

- Create a SecureRandom object
- Create a byte array of the appropriate length
- Use the SecureRandom to fill the byte array with random bytes

That should generate a key from the entire key space, uniformly at random—or at least as close as the SecureRandom gets us.

**Comment by leleuj** [comment]
OK. That makes sense. Would you mind submitting a PR for that? Thanks

**Comment by jonaskoelker-jypo** [comment]
See https://github.com/pac4j/play-pac4j/pull/273
