### ISSUE TITLE
ShiroAesDataEncrypter(final String key) makes suboptimal use of the key

### ISSUE THREAD

**Issue by jonaskoelker-jypo** [pac4j/play-pac4j#272]
The single-argument constructor at https://github.com/pac4j/play-pac4j/blob/master/shared/src/main/java/org/pac4j/play/store/ShiroAesDataEncrypter.java#L31 uses the argument on line 34 as follows: `this.key = key.getBytes(StandardCharsets.UTF_8)`.

Some byte arrays cannot possible be generated by this method. For example, the byte array where every byte has value 170 (= 0xAA = -86) is not a valid UTF8 sequence.

The practical consequence of this is that if a ciphertext is constructed with the all-170 key, ShiroAesDataEncrypter cannot decrypt it, as it can never have the right key.

I don't think there is a canonical surjective mapping from java.lang.String values to byte sequences; not even to byte sequences of some fixed length (e.g. 16 bytes or 128 bits, i.e. the AES key size).

My best idea is to deprecate this constructor and add a constructor which takes a byte array, leaving it up to the user of the library to map strings to byte arrays.

I guess some common ways of representing a byte array as a string is by base64 or hex encoding it. You may want to offer the user some facilities for doing this conversion.

**Comment by leleuj** [comment]
Yes, good idea. Would you mind submitting a PR for that also?

**Comment by jonaskoelker-jypo** [comment]
See https://github.com/pac4j/play-pac4j/pull/273

**Comment by leleuj** [comment]
I will release a new version 8.0.2 tomorrow...
