### ISSUE TITLE
Empty sessions saved in cache

### ISSUE THREAD

**Issue by DraganRaicici** [pac4j/play-pac4j#317]
We've noticed that play-pac4j saves creates session for every request and, if empty, they are saved in the cache. We use a redis cache and this behaviour would mean that we would fill up our cache really quick with essentially empty sessions. Is this something you are interested in looking into?

**Comment by leleuj** [comment]
Can you elaborate on this? What `PlaySessionStore`? ...

**Comment by DraganRaicici** [comment]
We are using the `PlayCacheSessionStore`.

**Comment by leleuj** [comment]
OK. "play-pac4j saves creates session for every request": what do you mean by that?

A session should only be created by play-pac4j when there is something to put in it (the `set` method).

**Comment by DraganRaicici** [comment]
I looked more into it and if we're accessing the site with an anonymous client, and no other client authorizes me, then it saves something in the cache, but the session cookie is not saved. Which means that the session, or profile, for every request that succeeds, gets saved in the cache. In our cache, since the cache is a db, this coupled with multiple offline page views, results in our database to potentially overflow. I can take a deeper dive into it so I can be even more precise, if you'd like :)

**Comment by leleuj** [comment]
I see several times in the logs: "generated sessionId: xxx", which may be the root cause. The sessionId should be generated only once per request. I'll investigate...

**Comment by DraganRaicici** [comment]
Great! However, I'm thinking that this might still not be enough. Even though the sessionId is not recreated for the same session, it still means that an anonymous session is saved in the cache. Is it possible to not save the anonymous sessions in the cache?

**Comment by leleuj** [comment]
As a first step, can you try play-pac4j v9.0.0-RC4-SNAPSHOT and see if only one session is generated per request? Thx

**Comment by DraganRaicici** [comment]
yes, of course, thank you for the quick fix.

**Comment by DraganRaicici** [comment]
Hmm...that wasn't it. It's still saving new objects in the cache everytime I refresh the same view (so it should be the same session). I will take a closer look at it to see the component that's causing this behaviour. And I set the version of play-pac4j to 9.0.0-RC4-SNAPSHOT.

**Comment by DraganRaicici** [comment]
So after some more debugging, I verified that when using the anonymous client, the PLAY_SESSION cookie is not set in the browser, and so, I assume, it results in the creation of different pac4jSessionIds.

Afterwards, I tried to login and then logout. The PLAY_SESSION cookie remained set with the sessionId I was given and there were no new sessionIds created until I removed the cookie by hand. Hope this give you some insight into where to look into, when you have the time, of course :smile:  Thank you for your time for now. I will look into it more tomorrow.

**Comment by leleuj** [comment]
I had the same issue: every refresh of the page generated a new sessionId. I just committed one more improvement to deal with that. You may need to use the `supplementResponse` method on the result if you create your own `PlayWebContext`.

**Comment by DraganRaicici** [comment]
Hi Jerome, 
After some fiddling today, I found out that the session is still being recreated. We are not creating our own `PlayWebContext`.

I found out that the object that's being put in the cache, for every request, with a new sessionId, is the `pac4jCsrfToken`.

**Comment by leleuj** [comment]
OK. So this is generated by the default `matchers` configuration which is `crsfToken`. Can you switch to `none`? Thx

**Comment by DraganRaicici** [comment]
I tried not adding the `crsfToken` to the cache. That solved the problem with caching filling up when called with the anonymous Client,but now, we're getting a `[CompletionException: org.pac4j.core.exception.TechnicalException: State parameter is different from the one sent in authentication request. Session expired or possible threat of cross-site request forgery]`.

This tells me that the token is needed in the cache, but then, the underlying problem of the sessionId recreating itself is still something we have to address.

The PLAY_SESSION cookie is not set when not logged in and browsing/refreshing the pages via the anonymous client, is this potentially a bug,or is it intended behaviour?

**Comment by leleuj** [comment]
The state parameter is something different from the CSRF token, but both are stored in the session so you need the session in some login processes.

Are you sure you tested with the latest play-pac4j v9.0.0-RC4-SNAPSHOT?

I use the following demo for my tests: https://github.com/pac4j/play-pac4j-java-demo and the sessionId is no longer re-generated when refreshing the index page. with the latest 9.0.0-RC4-SNAPSHOT.

**Comment by DraganRaicici** [comment]
Yes, I am sure I was using the latest  play-pac4j v9.0.0-RC4-SNAPSHOT because I pulled the latest changes from the repository and added some custom logging and saw them in my output.
We are not creating our own PlayWebContext as you are in the play-pac4j-demo. I will try to implement that throughout our project and see if it helps.

**Comment by DraganRaicici** [comment]
I was looking at the comments and noticed that I forgot to mention that we're implementing play-pac4j in Scala.

**Comment by DraganRaicici** [comment]
I made some changes to the play-pac4j-demo project to mimic the behaviour that we experience with sessionIds that we've been discussing :) 

Please check this pull request:
https://github.com/pac4j/play-pac4j-scala-demo/pull/79

**Comment by DraganRaicici** [comment]
We cannot use the `PlayCacheCookieStore` because the size of the cookie gets larger than 4KB, as described here: 
https://www.playframework.com/documentation/2.7.x/ScalaSessionFlash#How-it-is-different-in-Play

**Comment by leleuj** [comment]
I tested in Java and didn't see the issue. Now I can reproduce your problem with the Scala demo. I will investigate...

**Comment by leleuj** [comment]
OK. I got it. Things are a bit tricky. By default, the `PlayWebContext` holds the data (cookies, session, ...) necessary for the response. A call is needed to the `supplementResponse` method to add that data to the `Result`.
This only happens when the *pac4j* framework returns a `Result`. With the `AnonymousClient`, the request is passed through by the `Secure` function (notice the request is also supplemented) and *pac4j* does not return a `Result`.

So for each call on the `AnonymousClient` URL, a new session would be generated and lost.

Since play-pac4j v9.0.0-RC4-SNAPSHOT, the session id is also saved as a request attribute and saved as the request is supplemented. If you create a new `PlayWebContext` and calls the `SessionStore` the session id from the request is restored in the session and the `Result` can be correctly supplemented.

To make it short, you need to add this code:

```java
    val webContext = new PlayWebContext(request, playSessionStore)
    val sessionStore = webContext.getSessionStore().asInstanceOf[SessionStore[PlayWebContext]]
    sessionStore.getOrCreateSessionId(webContext)
    webContext.supplementResponse(Ok(views.html.index(...)).asJava).asScala
```

**Comment by SoerenSilkjaer** [comment]
> OK. I got it. Things are a bit tricky. By default, the `PlayWebContext` holds the data (cookies, session, ...) necessary for the response. A call is needed to the `supplementResponse` method to add that data to the `Result`.
> This only happens when the _pac4j_ framework returns a `Result`. With the `AnonymousClient`, the request is passed through by the `Secure` function (notice the request is also supplemented) and _pac4j_ does not return a `Result`.
> 
> So for each call on the `AnonymousClient` URL, a new session would be generated and lost.
> 
> Since play-pac4j v9.0.0-RC4-SNAPSHOT, the session id is also saved as a request attribute and saved as the request is supplemented. If you create a new `PlayWebContext` and calls the `SessionStore`, the session id from the request is restored in the session and the `Result` can be correctly supplemented.
> 
> To make it short, you need to add this code:
> 
> ```java
>     val webContext = new PlayWebContext(request, playSessionStore)
>     val sessionStore = webContext.getSessionStore().asInstanceOf[SessionStore[PlayWebContext]]
>     sessionStore.getOrCreateSessionId(webContext)
>     webContext.supplementResponse(Ok(views.html.index(...)).asJava).asScala
> ```

Shouldn't this be a native part of play-pac4j?

**Comment by leleuj** [comment]
I wish so, but I don't see any solution. The design of the `Secure` function is to pass the `request`, w don't have access to the `Result` as far as I know.
I'm working on another solution, which does not rely on knowing the intricates of play-pac4j...

**Comment by leleuj** [comment]
If you use the latest `play-pac4j` v9.0.0-SNAPSHOT and `pac4j` v4.0.0-SNAPSHOT, you have now a better solution:

You can define that you don't want to load the profiles from the session for the `AnonymousClient`:

```java
public class CustomProfileStorageDecision <C extends WebContext> implements ProfileStorageDecision<C> {

    @Override
    public boolean mustLoadProfilesFromSession(final C context, final List<Client> currentClients) {
        return isEmpty(currentClients) || currentClients.get(0) instanceof IndirectClient;
    }

    @Override
    public boolean mustSaveProfileInSession(final C context, final List<Client> currentClients,
                                            final DirectClient directClient, final UserProfile profile) {
        return false;
    }
}
```

and then use it in your configuration:

```java
    val logic = new DefaultSecurityLogic
    logic.setProfileStorageDecision(new CustomProfileStorageDecision[WebContext])
    config.setSecurityLogic(logic)
```

That way, no profile will be retrieved from the session and no session will be created for the `AnonymousClient`.

**Comment by DraganRaicici** [comment]
Hi Jerome. Interesting solution...but... We can still see sessions being created with the csrfToken stored in them. These sessions are saved in the cache and since we use a db cache, we are filling up our db with new sessions with, I guess, new csrfTokens for each request.

**Comment by leleuj** [comment]
You must also disable the CSRF tokens with `matchers = "none"`.

**Comment by DraganRaicici** [comment]
Can you point me in the right direction? This is a little vague for me.

**Comment by DraganRaicici** [comment]
Yes! The matchers="none" fixed our recurring sessions in the db
Thank you very much!

**Comment by DraganRaicici** [comment]
What is the implication of having the matchers="none" ? For now, we can see that our login didn't break and everything still seems to work as expected,but we are curious about that question :)

**Comment by leleuj** [comment]
By default, matchers are `securityHeaders,csrfToken`. It means that security headers will be added to the request and that the CSRF token will be computed. `none` means nothing happens.
You could just use `securityHeaders` in fact.
http://www.pac4j.org/docs/matchers.html
