### ISSUE TITLE
Supporting PKCE?

### ISSUE THREAD

**Issue by ndlarsen** [pac4j/play-pac4j#322]
Hi.

So, I aplogize in advance if this is already present in the documentation as in that case I have failed to locate it properly. I have been looking through the docs and I am wondering if play-pac4j (and pac4j) supports PKCE. If PKCE is indeed supported, would you be so kind to direct me to the doc/code related to this?

Thanks

**Comment by leleuj** [comment]
Next time, please ask your questions on the mailing list: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users

We don't support PKCE for OAuth.

**Comment by ndlarsen** [comment]
Are there any plans to?

**Comment by leleuj** [comment]
None that I'm aware of.
