### ISSUE TITLE
Incompatible changes to `CallbackController.callback()` have not been explained

### ISSUE THREAD

**Issue by jonaskoelker-jypo** [pac4j/play-pac4j#325]
Commit 0c13def03f8caf6604a83703fe1689fc0442ce47 makes backward-incompatible changes to the `callback` method on the `CallbackController`.

It would be nice if this was reflected at https://github.com/pac4j/play-pac4j/wiki/Callback-configuration, and if migration steps were mentioned on https://github.com/pac4j/play-pac4j/wiki/Migration-guide.

The particular compile error (excerpt) is this:
```
[error] /home/jonas/src/jp-frontpage/conf/routes:14:1: not enough arguments for method callback: (x$1: play.mvc.Http.Request)java.util.concurrent.CompletionStage[play.mvc.Result].
[error] Unspecified value parameter x$1.
[error] GET         /callback                                @org.pac4j.play.CallbackController.callback()
```

This is with scala 2.12.10, play 2.7.2 and `"org.pac4j" %% "play-pac4j" % "9.0.0-SNAPSHOT"`.

Note that the commit also makes a similar change to `LogoutController.logout()`, and the two mentioned controllers are the only files with `Controller` in their name which are changed in that commit—i.e. AFAICT those are the only two backwards-incompatible controller changes; although other changes may be incompatible as well.

**Comment by leleuj** [comment]
Good catch! It's fixed
