### ISSUE TITLE
AnonymousClient doesn't seem to work for the callback

### ISSUE THREAD

**Issue by rania-globalorange** [pac4j/play-pac4j#329]
I upgraded play-pac4j to 9.0.0 with play 2.7.4 in java and I have issues with the security rules. As far as I understood the _anonymous_ authorizer has been replaced by the AnonymousClient, but it doesn't seem to work for the callback. It works for the root, but when I access my secured endpoint I am redirected to the login page (of Keycloak in my case), where I login and then go to the callback but I am getting a 401. I remember from the previous version that the callback needs to be publicly accessible, but if the AnonymousClient is not the way to do it then what is the right way?

This is my configuration:

`pac4j.security.rules = [
  {"/api.*" = {
    clients = "KeycloakOidcClient"
  }}
  {"/" = {
    clients = "AnonymousClient"
  }}
  {"/callback.*" = {
    clients = "AnonymousClient"
  }}
  {".*" = {
    clients = "KeycloakOidcClient"
  }}
]`

**Comment by leleuj** [comment]
There might be an issue here. I will check.

**Comment by leleuj** [comment]
Indeed, there is a core issue in pac4j when the security filter protects the callback endpoint. I'll fix that in a future version of pac4j.

Currently, you should use this configuration:

```
{"/callback.*" = {
}
```

Can you check that it works with the version 9.0.1-SNAPSHOT? Thx

**Comment by rania-globalorange** [comment]
As far as I can see the fix is on master, there is no release for it. But I am unable to include this successfully in my play project and test it. I tried with adding the jar in `project/lib` and I also tried with adding dependsOn and the uri but no success. Any idea is welcome.

**Comment by leleuj** [comment]
The fix is available for version 9.0.1-SNAPSHOT (Play 2.7) and version 10.0.1-SNAPSHOT (Play 2.8).
Both development versions are available in the Sonatype Snapshots repository. See: https://github.com/pac4j/play-pac4j-java-demo/blob/master/build.sbt#L49

```
resolvers ++= Seq(Resolver.mavenLocal, "Sonatype snapshots repository" at "https://oss.sonatype.org/content/repositories/snapshots/", "Shibboleth releases" at "https://build.shibboleth.net/nexus/content/repositories/releases/")
```

**Comment by rania-globalorange** [comment]
Oops, I missed that. Thanks, it all works now!

**Comment by leleuj** [comment]
Perfect! I will cut the 9.0.1 / 10.0.1 releases soon.
