### ISSUE TITLE
PlayCookieSessionStore fails to deserialize a CodeVerifier

### ISSUE THREAD

**Issue by daddykotex** [pac4j/play-pac4j#340]
Changes for PKCE from pull request #1630 introduce a problem. One of the problem was that a CodeVerifier was not serializable, but it has been fixed upstream. By forcing the version `"com.nimbusds:oauth2-oidc-sdk:8.11"`, the class cast exception to serialization is fixed.

But there is another problem a little bit further down the rabbit hole. The Oidc process and the introduction of PKCE saves a CodeVerifier in the SessionStore. If you use `PlayCookieSessionStore`, on top of being `Serializable`, the internal implementation of `PlayCookieSessionStore` uses an instance of `JavaSerializationHelper` which is too restrictive and cannot serialize a `byte[]`. The `CodeVerifier` extends `Secret` which includes a `byte[]`. 

The simplest reproduction can be done like this:

```java
final JavaSerializationHelper JAVA_SER_HELPER = new JavaSerializationHelper();
JAVA_SER_HELPER.deserializeFromBytes(JAVA_SER_HELPER.serializeToBytes(new CodeVerifier()));
```

There is a work around where we can add a trusted package and it works:

```java
PlayCookieSessionStore.JAVA_SER_HELPER.addTrustedPackage("[B")
```

The correct fix would be to add this to the internal list in `JavaSerializationHelper`.

I can open a PR if you think I'm right. If not, let me know what you can think and maybe I can still address it in a PR.

Thanks again for the library.

**Comment by leleuj** [comment]
It make sense. Please submit a PR to `pac4j`. Thx

**Comment by daddykotex** [comment]
Thanks for your project
