### ISSUE TITLE
DDOS susceptibility: stuck between a rock cookie and a cache hard place

### ISSUE THREAD

**Issue by jonaskoelker-jypo** [pac4j/play-pac4j#344]
Hello Jerome.

I'm in a bit of a pickle: my OidcClient profiles are too large to store using the `PlayCookieSessionStore`, as much as I would like to. On the other hand, our site has a lot of visitors who don't log in so we need to store a large number of anonymous profiles. This is especially exacerbated when we're subjected to a distributed denial of service attack, by users who trigger the creation of a new anonymous profile each session—using the `PlayCacheSessionStore` backed by (e.g.) a Redis instance means that attackers can exhaust our storage space.

Do you have any recommendations about what can be done?

My first idea would be to store anonymous profiles in cookies and non-anonymous profiles in Redis. I figure you know pac4j better than I do, so maybe you can come up with something even better. If not, could you give me a few pointers on the best way to have a split/dual storage?

Thanks for your time and consideration :)

**Comment by leleuj** [comment]
Hi, please use the mailing list for questions: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users
