### ISSUE TITLE
Jackson dependency issue

### ISSUE THREAD

**Issue by GBeushausen** [pac4j/play-pac4j#357]
I had play-pac4j working in a 2.6 app fine. Now i started a brand new project using 2.8.2. As soon as i add pac4j-http to the dependencies, i get the following error message:

com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.10.3 requires Jackson Databind version >= 2.10.0 and < 2.11.0

It doesn't matter if i install the Jackson dependencies. I always receive this error message.

**Comment by leleuj** [comment]
I think you should take a look at the mailing list: https://groups.google.com/g/pac4j-users/c/mVSlxxlY9kA/m/MSTvXy4SBwAJ
