### ISSUE TITLE
Jackson version conflict between Play and pac4j

### ISSUE THREAD

**Issue by marcadella** [pac4j/play-pac4j#382]
Play 2.8 uses Jackson 2.10, while pac4j-oidc uses Jackson 2.11. 2.10 is therefore evicted and makes Play unhappy:
```
com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.10.5 requires Jackson Databind version >= 2.10.0 and < 2.11.0
```

**Comment by ndmckinley** [comment]
I fixed this by adding

```
dependencyOverrides ++= Seq(
  "com.fasterxml.jackson.core" % "jackson-databind" % "2.10.5",
  "com.fasterxml.jackson.core" % "jackson-core" % "2.10.5",
  "com.fasterxml.jackson.core" % "jackson-annotations" % "2.10.5",
)
```

to `build.sbt`.  It's not a perfect solution but it got me going again at least.  Diamond dependencies are the worst.

**Comment by leleuj** [comment]
I tried several things, but this is not possible at the library level.

So the solution is to explicitly exclude dependencies.
