### ISSUE TITLE
Disable authentication globally

### ISSUE THREAD

**Issue by michel-kraemer** [pac4j/play-pac4j#39]
Is it possible to disable authentication for the whole application by setting a certain configuration value or something like that? For example, if you want to do integration tests?

Thanks,
Michel

**Comment by hugovalk** [comment]
With the upcoming 1.5.0 (Play 2.4) release, play-pac4j can use dependency injection to setup the configured clients. 

You can create a normal SecurityConfig class containing for example a SAML2 client and you could have a dummy SecurityConfig class that authenticates via basic authentication and the test user name password (like in the demo application) to use in the integration tests. 
The dependency injection modules are configured in application.conf and can therefore be swapped. 

Please refer to the README and to the Play 2.4 documentation on Dependency Injection:
https://www.playframework.com/documentation/2.4.x/ScalaDependencyInjection

**Comment by samudurand** [comment]
For anyone interested, I had exactly the same requirement today and the best method I found is to disable the security by using the AnonymousClient
```scala
class NoSecurityModule(environment: Environment, configuration: Configuration) extends AbstractModule {

  def configure() = {
    val anonymousClient = new AnonymousClient()
    // set this name identical to the ldap client to use the app with disabled security
    anonymousClient.setName("ldap")

    val clients = new Clients(anonymousClient)
    clients.init()

    val config = new Config(clients)
    config.setHttpActionAdapter(new DefaultHttpActionAdapter())

    bind(classOf[Config]).toInstance(config)
    bind(classOf[PlaySessionStore]).to(classOf[PlayCacheSessionStore])
  }

}
```

Then you simply have to switch between the two modules in the application.conf to enable/disable security check
