### ISSUE TITLE
Bytecode compatibility play-pac4j_2.13

### ISSUE THREAD

**Issue by cchantep** [pac4j/play-pac4j#391]
It seems that the latest release for play-pac4j_2.13 was only done for Java 11... Unfortunately a lot of environment require that compatibility with the (really) long term Java version 8, so this can be compatible.

**Comment by leleuj** [comment]
Yes, the new version is based on JDK 11. Older versions are still based on JDK 8.

**Comment by cchantep** [comment]
That's a major requirement that should at least be clearly documented.

**Comment by leleuj** [comment]
I added it in the README.
