### ISSUE TITLE
CAS response with utf-8 encoding

### ISSUE THREAD

**Issue by jiangzhe** [pac4j/play-pac4j#51]
I've got a problem that CAS response XML encoded in utf-8 can not be correctly parsed. Is there a way to make the cas client to use specific encoding (e.g. utf-8) for parsing result? 
I checked the jasig library used for CAS validation has setEncoding method. Is it ok to pass the encoding after creating the CasClient?

**Comment by leleuj** [comment]
The `setEncoding` method is not exposed in the pac4j `CasClient`. Either you set the encoding at the JVM level and it fixes the problem or you can propose a PR to add this encoding method in pac4j. Thx

**Comment by leleuj** [comment]
Any update on this? Any PR to add a `setEncoding` method to the `CasClient`?

**Comment by leleuj** [comment]
Replaced by: https://github.com/pac4j/pac4j/issues/242
