### ISSUE TITLE
Saml2Profile is not populating roles.

### ISSUE THREAD

**Issue by anishdevasia** [pac4j/play-pac4j#56]
When integrated with SAML provider profile is not loading roles given by the provider.

**Comment by leleuj** [comment]
It should work. The `BaseClient` has the `getUserProfile` method which relies on the `retrieveUserProfile`method: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/client/BaseClient.java#L234 and computes the roles according to the provided authorization generators. The `Saml2Client` only implements the `retrieveUserProfile` method.

Would you mind providing me with further details? Thanks
