### ISSUE TITLE
Documentation states that 1.4.0 is the latest Java release, but it hasn't been built/pushed to the Maven repo

### ISSUE THREAD

**Issue by nateww** [pac4j/play-pac4j#57]
The documentation states that 1.4.0 is the latest release, but it doesn't exist:

http://mvnrepository.com/artifact/org.pac4j/play-pac4j_java

Can you either update the documentation to use the 1.3.0 release, or push up a new release?

**Comment by leleuj** [comment]
I'm on my way for the new release...

**Comment by nateww** [comment]
I still don't see 1.4.0 on the mvn repo above, and I noticed you announced the release on the play mailing lists...

**Comment by leleuj** [comment]
Yes, it is on repo1.maven.org
http://search.maven.org/#search%7Cga%7C1%7Cplay-pac4j

**Comment by nateww** [comment]
My apologies, I assumed it would show up on the URL above.  Thanks for doing this!

**Comment by leleuj** [comment]
No problem.
