### ISSUE TITLE
Play 2.4.x support?

### ISSUE THREAD

**Issue by sefator** [pac4j/play-pac4j#58]
Are there plans to support Play 2.4.x ?

**Comment by leleuj** [comment]
Yes.

Here is the plan: add REST support (+ LDAP + DB supports...) in `pac4j` v1.8 and then update `play-pac4j` with this new version: I may only target Play 2.3 & 2.4 supports though.

But before that, we could certainly update the current master to support Play 2.4 and 2.3 (same version 1.4.x) or create a new version (1.5.0) to only support Play 2.4 if it's not compatible. Any contribution will be appreciated.

**Comment by hugovalk** [comment]
Hi,
I've submitted a pull request with some updates on working with Play 2.4. 

Play 2.4 is not binary compatible with Play 2.3, therefore you need to recompile the project. Probably you will need a version 1.5. 

play-pac4j does not work with dependency injected routes at this moment, so either people need to use old style controllers or the project might be updated to use the new style controllers as well, but in that case existing projects using play-pac4j need to be updated.

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/play-pac4j/pull/63

**Comment by leleuj** [comment]
Thank you for your help on Play 2.4.

There is an ambitious roadmap for `play-pac4j` using the new capabilities of the incoming `pac4j` v1.8: feel free to get involved and pick the latest issues ;-)
