### ISSUE TITLE
Upgrade to pac4j 1.8

### ISSUE THREAD

**Issue by leleuj** [pac4j/play-pac4j#59]

**Comment by PR-O** [comment]
Hi @leleuj , is there an ETA on this upgrade?

**Comment by leleuj** [comment]
Yes, I'll start that next week.

**Comment by PR-O** [comment]
Cool!

**Comment by PR-O** [comment]
Any news on this @leleuj ?

**Comment by leleuj** [comment]
Yes, I'm working on it. I've made a huge refactoring of the library. It's almost done, I need to review everything again, test a little more and write the full documentation. Hope it will be ready for the end of this week or the beginning of the next one.

**Comment by PR-O** [comment]
That's great news!

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/play-pac4j/pull/73

**Comment by leleuj** [comment]
@PR-O : any feedback will be appreciated on the new v2 (#73), demos have been updated as well: https://github.com/pac4j/play-pac4j-java-demo/pull/19 & https://github.com/pac4j/play-pac4j-scala-demo/pull/18

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/play-pac4j/pull/77
