### ISSUE TITLE
Missing state parameter

### ISSUE THREAD

**Issue by KentaKomai** [pac4j/play-pac4j#66]
First thanks for creating pac4j. It is  very useful libraries.

I use `"org.pac4j" % "play-pac4j_scala2.11" % "1.4.0"` and `"org.pac4j" % "pac4j-oauth" % "1.7.0"` on Play framework 2.3.

I am trying to implement a Facebook login in my web application.
However, errors such as the following: I have out.

```
play.api.Application$$anon$1: Execution exception[[OAuthCredentialsException: Missing state parameter : session expired or possible threat of cross-site request forgery]]

at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.8.jar:2.3.8]
	at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.8.jar:2.3.8]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [play_2.11-2.3.8.jar:2.3.8]
	at scala.Option.map(Option.scala:146) [scala-library-2.11.6.jar:na]
Caused by: org.pac4j.oauth.client.exception.OAuthCredentialsException: Missing state parameter : session expired or possible threat of cross-site request forgery
	at org.pac4j.oauth.client.BaseOAuth20Client.getOAuthCredentials(BaseOAuth20Client.java:86) ~[pac4j-oauth-1.7.0.jar:na]
	at org.pac4j.oauth.client.BaseOAuthClient.retrieveCredentials(BaseOAuthClient.java:128) ~[pac4j-oauth-1.7.0.jar:na]
	at org.pac4j.oauth.client.BaseOAuthClient.retrieveCredentials(BaseOAuthClient.java:45) ~[pac4j-oauth-1.7.0.jar:na]
	at org.pac4j.core.client.BaseClient.getCredentials(BaseClient.java:220) ~[pac4j-core-1.7.0.jar:na]
	at org.pac4j.play.java.RequiresAuthenticationAction$6.apply(RequiresAuthenticationAction.java:202) ~[play-pac4j_java-1.4.0.jar:na]
```

This error will appear after it has approved the application on Facebook.
When I get an error, URL is as follows:

```
/oauth/callback?
client_name=FacebookClient
&code=[random string]
state=Pw2EftzrLD#_=_
```

Will you have a setting not something well?
It is operating normally in Twitter

Thank you.

**Comment by KentaKomai** [comment]
After, it had come out also, such as the following log.

```
[debug] o.p.o.c.BaseOAuth20Client - sessionState : null / stateParameter : 1tNIJL8WEf
```

**Comment by leleuj** [comment]
Hi,

It's not the first time this "issue" is reported: as this `state` parameter is saved into the web session, the problem generally comes from a session issue (configuration).
You should really take a look at the mailing list where various solutions has been discussed: https://groups.google.com/forum/#!forum/pac4j-users

Best,

**Comment by blemoine** [comment]
T.L.D.R : state isn't saved in session but in memory.

I've the same problem and after hours of search, it's seems that the pac4j implementation saving the "state" is stateful. 

The class org.pac4j.play.scala.ScalaWebContext, in the methods get/set SessionAttributes use something called StorageHelper, which backend is in fact an in memory cache. 
Creating my own ScalaContext and my own ScalaController solved this problem, by using a mutable map for session ( I'm so sad...) and applying an updated session with this map in the controller.

**Comment by leleuj** [comment]
Indeed, nothing goes into the session except an identifier, everything else (tokens, states, profiles) goes into the Cache (using the StorageHelper class). As the session is held in a cookie (in all HTTP requests, limited to 4K), it's a good practice to only store the identifier in the session and other things in the Cache.

That said, it should work with the Cache and it works in the demo: https://github.com/pac4j/play-pac4j-java-demo & https://github.com/pac4j/play-pac4j-scala-demo

I'm working on a rebuild of the library based on the new pac4j version 1.8: it's the perfect time for suggestions and contributions.

**Comment by blemoine** [comment]
The problem arise when you have multiple play framework with a Load Balancer in front of them. 

Eg. : 
 - The user ask for the redirectURI
 - The Load Balancer redirect the request to the first Play Framework
 - The first play framework store the state in it's Cache and respond correctly with the redirect
 - After authorization, the user is redirected to the callbackURL
 - The load balancer redirect the request to the second Play framework
 - The second play framework hasn't the state in it's cache, and it answer with the above error.

**Comment by leleuj** [comment]
You're right: if you use a load balancer, you need to share your Cache accross your instances, where as your session is shared by default between your instances. Though, it's a common pattern and I don't see it as a problem. Except that maybe the documentation should be improved.

Were you expected to have everything in the session?

**Comment by blemoine** [comment]
Yes, it's not a problem when you know it works like that :) 

For my specific needs, I expected it to be in session, because the only parameter that was needed was the "state".  That's why I wrote my own "ScalaWebContext" and my own "ScalaController". 

On the suggestion point, maybe you can, in the next version, reduce the coupling between ScalaController and ScalaWebContext to easily inject another context type. In my case it would have been perfect :)

(By the way, thanks for pac4j, everything else worked perfectly fine :) )

**Comment by leleuj** [comment]
I definitely need to improve the documentation, I agree, to prevent people from spending time for nothing.

I'm currently working on a new implementation and based on the new DI capabilities of Play and the new capabilities of pac4j v1.8, I plan to do something really easier yet powerful with a pluggable storage mechanism.

**Comment by leleuj** [comment]
For play-pac4j version 2.0, the `StorageHelper` has been removed and there is now a `CacheStore`: its name obviously states how it works. I also updated the documentation to avoid people to have the same issue: https://github.com/pac4j/play-pac4j/pull/73/files#diff-04c6e90faac2675aa89e2176d2eec7d8R174
