### ISSUE TITLE
Issues with live demo application

### ISSUE THREAD

**Issue by dan-lind** [pac4j/play-pac4j#67]
The current live demo application seems to have several issues:

"Authenticate with Facebook" gives "This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions"

"Authenticate with CAS" gives "This webpage is not available"

"Authenticate with SAML" asks me for a username and password (perhaps this is correct, not sure)

"Authenticate with Google OpenID" gives something like (translated) "OpenID 2.0 for Google-accounts is no longer in use"

**Comment by leleuj** [comment]
Yes, there might be some glitches.

Regarding Facebook issue, maybe I need to do something in the Facebook console, things are constantly changing...

Regarding CAS issue, you need a real CAS server on localhost:8888.

For SAML, I thought login / passwords where displayed under the login page.

Regarding OpenID Google support, it should be cleaned as it has been deprecated.

Maintaining all `pac4j` demos is a tremendous job: any contribution will be appreciated.

**Comment by leleuj** [comment]
With the new play-pac4j v2.0, the demos will be fully tested and updated.
