### ISSUE TITLE
How to log in an account from the back-end

### ISSUE THREAD

**Issue by PR-O** [pac4j/play-pac4j#68]
Hi!

Great work on Play-Pac4J, we're happily outsourcing part of our authentication using Pac4J :smile: !

Quick question: we want to be able to log in a user using an email link (e.g. confirm email link after registration or a 'magic link'). What's the best way to do so using Pac4J?

**Comment by leleuj** [comment]
Currently, play-pac4j is based on pac4j v1.7. I'm going to upgrade it with pac4j v1.8 in the next few days. It's going to be easier with pac4j v1.8.

The registration part is not done by pac4j: a user fills a form and he is created into your database (for example) and a token is generated. Then, a link with this token is sent to the user email.

On a specific url, you need to define a [ParameterClient](https://github.com/pac4j/pac4j/blob/master/pac4j-http/src/main/java/org/pac4j/http/client/direct/ParameterClient.java) which will get the provided token and pass it to your `SpecificTokenAuthenticator` which will fetch the user profile from the database based on the token. Saves this user profile in the current credentials and use a `AuthenticatorProfileCreator`: the user will be authenticated this way.

With pac4j v1.7, it would be harder: you would need to create the `ParameterClient` on your own, a specific `Credentials` also to pass the user profile to the `ProfileCreator` and the `AuthenticatorProfileCreator`.

**Comment by PR-O** [comment]
Right! I hadn't seen the ParameterClient before! Seems suitable for our use case. Our token authenticator is ready to go :smile: , so I guess we'll just wait for 1.8! Great timing!

Thanks for your clear answer.
