### ISSUE TITLE
Play pac4j 1.5.0 not released

### ISSUE THREAD

**Issue by pycloux** [pac4j/play-pac4j#69]
Hi Jérôme,

Just to be 100% sure, play-pac4j 1.5.0 has not yet been released ?
(I can only find the 1.4.0 in the repo).
So I assume that only snapshots are available.

Best regards,

PYC

**Comment by leleuj** [comment]
You're right: planning to do in the next few days. Did you test it successfully? No bug to report?

**Comment by pycloux** [comment]
I am just about to upgrade.
I'll tell you in a few days :-)

**Comment by leleuj** [comment]
I just released the version 1.5.0, it should be available in the Maven central repository in a few hours.
