### ISSUE TITLE
Support for cache prefix specific to sessions.

### ISSUE THREAD

**Issue by princegoyal1987** [pac4j/play-pac4j#70]

**Comment by leleuj** [comment]
I guess you find the solution on your own: https://github.com/pac4j/play-pac4j/blob/master/play-pac4j-java/src/main/java/org/pac4j/play/StorageHelper.java#L196

In the future 2.0 version, the design of the library will be improved, but this mechanism will be kept.

**Comment by leleuj** [comment]
Still there: https://github.com/pac4j/play-pac4j/blob/master/play-pac4j-java/src/main/java/org/pac4j/play/store/CacheStore.java#L106
