### ISSUE TITLE
PlayCookieSessionStore does not work with profiles storing dates

### ISSUE THREAD

**Issue by mkr** [pac4j/play-pac4j#705]
I am using the pac4j SAML integration but am not able to store an `org.pac4j.saml.profile.SAML2Profile` in the `PlayCookieSessionStore` anymore because the `ZonedDateTime` properties cannot be serialized. This worked in version 5 but no longer in 6.

In 4896bdb play-pac4j switched the serializer to the `org.pac4j.core.util.serializer.JsonSerializer`. The `JsonSerializer` uses Jackson's `ObjectMapper` with "default typing" since this [commit](https://github.com/pac4j/pac4j/commit/324bc589ab244368284d74a05c52a35b496f1e3b). This does not seem to support date types and will result in the error:
```
Type id handling not implemented for type java.lang.Object (by serializer of type com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer) (through reference chain: java.util.HashMap["notOnOrAfter"])
```

A fix might be to equip the JsonSerializer's ObjectMapper with the `JavaTimeModule` (and adding the `com.fasterxml.jackson.datatype:jackson-datatype-jsr310` dependency) and set some defaults, i.e.
```
objectMapper.registerModule(new JavaTimeModule());
objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
objectMapper.configure(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE, false);
```

Alternatively, just adding the `JavaTimeModule` and changing the type of the ZonedDateTime fields to Instant might be the better alternative (unless we strictly need the time zone).

Another temporary workaround might be to just switch back to Java serialization.

**Comment by leleuj** [comment]
Good point! Would you mind submitting a PR for that? Thx

**Comment by mkr** [comment]
Which solution do you prefer? Why did we switch from the JAVA_SERIALIZER to the JsonSerializer (we still use the JAVA_SERIALIZER in the [Vertx integration](https://github.com/pac4j/vertx-pac4j/blob/master/src/main/java/org/pac4j/vertx/context/session/VertxSessionStore.java), for example)? I am not sure if using Jackson with default typing provides a better solution for storing profiles in a cookie?

**Comment by leleuj** [comment]
I think Java serialization brings more problems than JSON serialization (JDK upgrade, Java class changes) so I prefer to add the missing `JavaTimeModule`.

**Comment by mkr** [comment]
Hi @leleuj, I've opened a PR in pac4j [here](https://github.com/pac4j/pac4j/pull/3084).

**Comment by leleuj** [comment]
It depends on what you mean by "soon" ;-) I plan to release pac4j v6.1.0 at the beginning of November
