### ISSUE TITLE
[Play 2.4-Java] Dependency problem with play-pac4j_java

### ISSUE THREAD

**Issue by PR-O** [pac4j/play-pac4j#72]
In my Play 2.4 project, I used to include the play-pac4j_java 1.5.0-SNAPSHOT dependency. That one can no longer be used as play-pac4j is moving to 1.5.1-SNAPSHOT. However, when I try the 1.5.0 version as a dependency, it can't be found. The dependency is as below:

          "org.pac4j" % "play-pac4j_java" % "1.5.0"

**Comment by jeroen4now** [comment]
Try (use - not _)
"org.pac4j" % "play-pac4j-java" % "1.5.0"

**Comment by leleuj** [comment]
Exactly

**Comment by PR-O** [comment]
Thanks! I now see the underscore was changed into a dash.
