### ISSUE TITLE
`setProviderMetadata` method missing from OidcConfiguration

### ISSUE THREAD

**Issue by asharma-yb** [pac4j/play-pac4j#726]
Trying to upgrade from play-pac4j 9.x -> 12.x and pac4j-oidc 4.x -> 6.x.
We use `oidcConfiguration.setProviderMetadata(OIDCProviderMetadata.parse(providerMetadata));` in the current implementation. 

The latest [docs](oidcConfiguration.setProviderMetadata(OIDCProviderMetadata.parse(providerMetadata));) mention `If you do not define the discoveryUri, you’ll need to provide the provider metadata via the setProviderMetadata method.` but I don't see the method defined in  [OidcConfiguration.java](https://github.com/pac4j/pac4j/blob/master/pac4j-oidc/src/main/java/org/pac4j/oidc/config/OidcConfiguration.java).

Am I missing something or is this a bug?
What can I use in the meanwhile to achieve the same functionality?
Thanks.

**Comment by leleuj** [comment]
This is done on purpose. You cannot set the provider metadata at the configuration level without passing by a `OidcOpMetadataResolver` which is meant to provide a certain number of features.

In your case, you need to use the `StaticOidcOpMetadataResolver`.

**Comment by asharma-yb** [comment]
Thanks for the response. 
As I said,
>The latest [docs](https://github.com/pac4j/play-pac4j/issues/oidcConfiguration.setProviderMetadata(OIDCProviderMetadata.parse(providerMetadata));) mention If you do not define the discoveryUri, you’ll need to provide the provider metadata via the setProviderMetadata method. but I don't see the method defined in [OidcConfiguration.java](https://github.com/pac4j/pac4j/blob/master/pac4j-oidc/src/main/java/org/pac4j/oidc/config/OidcConfiguration.java).

So the current docs are incorrect since there is no `setProviderMetadata` method anymore and should be updated to mention the new way of doing things. 
Thanks again 🙏

**Comment by leleuj** [comment]
Sure. Will update doc.
