### ISSUE TITLE
Exception after IndirectClient.getRedirectAction amount of params changed.

### ISSUE THREAD

**Issue by pepijnschildkamp** [pac4j/play-pac4j#76]
Hi,

After updating pac4j-play this week it seems there is some sort of reflection error. This might be due to the changes of isAjax parameter. The IndirectClient.getRedirectAction function changed from 3 to 2 parameters for pac4j-play. My guess is that the pac4j core is trying to invoke the function with 3 parameters via reflection and is unable to find it. See the stack trace below.   

```sh
java.lang.NoSuchMethodError: org.pac4j.core.client.IndirectClient.getRedirectAction(Lorg/pac4j/core/context/WebContext;ZZ)Lorg/pac4j/core/client/RedirectAction;
	at org.pac4j.play.java.RequiresAuthenticationAction.redirectToIdentityProvider(RequiresAuthenticationAction.java:197)
	at org.pac4j.play.java.RequiresAuthenticationAction$1.lambda$apply$1(RequiresAuthenticationAction.java:168)
	at org.pac4j.play.java.RequiresAuthenticationAction$1$$Lambda$48/1462577183.apply(Unknown Source)
	at play.core.j.FPromiseHelper$$anonfun$promise$2.apply(FPromiseHelper.scala:36)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by leleuj** [comment]
You're right, things have changed in pac4j v1.8: the `isAjax` parameter has been removed in favor of an automatic detection of the AJAX nature of an HTTP request.
But it should work without any error using play-pac4j v2.0. Can you elaborate a little more on your environment?

**Comment by pepijnschildkamp** [comment]
Hi Leleuj,

Thanks for your reply. 
Currently we are using Play framework 2.4.2 JAVA. 

See the sbt below for the used deps for pac4j. 

```sbt
libraryDependencies ++= Seq(
  "org.pac4j" % "play-pac4j-java" % "2.0.0-SNAPSHOT",
  "org.pac4j" % "pac4j-http" % "1.8.0-SNAPSHOT",
  ("org.pac4j" % "pac4j-cas" % "1.8.0-SNAPSHOT").exclude("org.opensaml", "opensaml"),
  "org.pac4j" % "pac4j-openid" % "1.8.0-SNAPSHOT",
  "org.pac4j" % "pac4j-oauth" % "1.8.0-SNAPSHOT",
  "org.pac4j" % "pac4j-saml" % "1.8.0-SNAPSHOT",
  "org.pac4j" % "pac4j-oidc" % "1.8.0-SNAPSHOT",
  "org.pac4j" % "pac4j-jwt" % "1.8.0-SNAPSHOT",
  "org.pac4j" % "pac4j-ldap" % "1.8.0-SNAPSHOT",
  "org.pac4j" % "pac4j-sql" % "1.8.0-SNAPSHOT",
  "org.pac4j" % "pac4j-mongo" % "1.8.0-SNAPSHOT"
)
```

**Comment by leleuj** [comment]
I just tested the https://github.com/pac4j/play-pac4j-java-demo and I don't have the problem. Are you sure you have the latest dependencies?

**Comment by pepijnschildkamp** [comment]
I have successfully ran the demo app. I think it's a dependency caching conflict at my local machine. When I browse to the pac4j-java 2.0 jar in IntelliJ there is still an reference to ```isAjax``` in the method [RequiresAuthenticationAction.redirectToIdentityProvider](https://github.com/pac4j/play-pac4j/blob/master/play-pac4j-java/src/main/java/org/pac4j/play/java/RequiresAuthenticationAction.java#L193). 

```java
    protected Result redirectToIdentityProvider(final Client client, final PlayWebContext context, final boolean isAjax) {
        try {
            final RedirectAction action = ((IndirectClient) client).getRedirectAction(context, true, isAjax);
            logger.debug("redirectAction: {}", action);
            return httpActionHandler.handleRedirect(action);
        } catch (final RequiresHttpAction e) {
            return httpActionHandler.handle(e.getCode(), context);
        }
    }
```

When browsing in this repo I see you have removed this parameter. I already removed all Ivy2 cache and regenerated the idea files. Still I got the wrong dependencies. Strange thing is; my colleague has exactly the same problem. Any ideas?

**Comment by leleuj** [comment]
I know. The latest build on play-pac4j has failed. It works locally for me as I have built the source code.
I restarted the build, it should be ok in a few minutes.

**Comment by pepijnschildkamp** [comment]
That makes sense. Thanks Leleuj for your quick response and actions. 
Do you have an public CI server so I can check if the build was successful?

**Comment by leleuj** [comment]
Yes: https://travis-ci.org/pac4j/play-pac4j. Currently in progress and very slow...

**Comment by leleuj** [comment]
Build passed.

**Comment by pepijnschildkamp** [comment]
Thanks Leleuj. I'm able to compile again :).
