### ISSUE TITLE
PLay 2.2 demo

### ISSUE THREAD

**Issue by abhijitbasu** [pac4j/play-pac4j#87]
Where can I find the Play 2.2 Pac4j demo

**Comment by leleuj** [comment]
In the *play22* branches:
https://github.com/pac4j/play-pac4j-scala-demo/tree/play22
https://github.com/pac4j/play-pac4j-java-demo/tree/play22

**Comment by abhijitbasu** [comment]
1. How do I access profile attributes like mail in java application. It say attributes are private
2. How do I use OAuth2 for Salesforce, seems there is no client already available

**Comment by leleuj** [comment]
As all profiles inherit from `CommonProfile`, you can call `getEmail`, `getFirstName` whatever the current profile is (https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/profile/CommonProfile.java).

You can also simply call `getAttribute(name)` to get an attribute by its name.

Indeed, there is currently no Salesforce client using OAuth 2.0 protocol. As the pac4j-oauth module rely on Scribe (https://github.com/scribejava/scribejava) and as there is no Salesforce implementation in it, you would need to do both: create a Scribe API (`org.scribe` package) and a pac4j client (`org.pac4j` packages) -> see: https://github.com/pac4j/pac4j/wiki/Clients#creating-your-own-client.
Any contribution will be highly appreciated. Thanks.
