### ISSUE TITLE
[play-pac4j-2.0.1] NullpointerException when setting null value in Redis Cache

### ISSUE THREAD

**Issue by PR-O** [pac4j/play-pac4j#90]
We are using Redis cache with our Play 2.4 application. After upgrading from play-pac4j 1.7.x to play-pac4j-java 2.0.1-SNAPSHOT, we get a NullPointerException originating from the IndirectClient.cleanAttemptedAuthentication() function (line 76) when logging in a user. Or more specifically when setting a session attribute after successfully authenticating a user.

This it the relevant line:
            context.setSessionAttribute(this.getName() + "$attemptedAuthentication", (Object)null);

I suspect play-pac4j 1.7.x did not set a null value in the cache?

When using Play's standard EhCache saving objects with null values in the cache does not seem to be a problem.

**Comment by leleuj** [comment]
Yes, this cleanup is a new feature from pac4j v1.8. We will have the issue twice as we clean elements from the session at the end of the login process: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/client/IndirectClient.java#L134

But we could safely use an empty String as tests are made using `CommonHelper.isNotBlank`.

Would you mind opening a pull request for that on the pac4j project? I guess we'll need to wait for pac4j v1.8.3 to release play-pac4j v2.0.1.

**Comment by PR-O** [comment]
Ok. See (https://github.com/pac4j/pac4j/issues/424)[https://github.com/pac4j/pac4j/issues/424].
