### ISSUE TITLE
Getting a hold of injected Config outside of Controllers

### ISSUE THREAD

**Issue by PR-O** [pac4j/play-pac4j#91]
In version 1.5.x we used to grab the pac4j session id in various places throughout our app, by doing the following:

    sessionId = StorageHelper.getOrCreationSessionId(context.session());

When upgrading to version 2.0.1-SNAPSHOT we changed this into:

    @Inject
    Config config;

    final WebContext webContext = new PlayWebContext(context, config.getSessionStore());
    sessionId = config.getSessionStore().getOrCreateSessionId(webContext);

This new manner of grabbing (or creating) the sessionId only seems to work in Controllers, is that right? Elsewhere (models, services) config remains null. As I'm still quite unfamiliar with Dependency Injection in Play 2.4.x I may be missing something here.

Any comments or best practices?

**Comment by leleuj** [comment]
Injection should work in all components using `@Inject` although I didn't test it outside controllers.

In all cases, you need the web context so I'm not sure how you can / could use that in models and services. Can you elaborate on this?

**Comment by PR-O** [comment]
Sure. We use Deadbolt for role management. As such, we have an AbstractDeadboltHandler class that is used to perform certain checks on requests before they even get to Controllers. That class gets a context. We used to check for a pac4J session id using the StorageHelper.getOrCreationSessionId() function. Now it seems we have no way of getting to the session store from AbstractDeadboltHandler :cry:.

**Comment by leleuj** [comment]
I'm surprised the `config` injection does not work. Though, if you want to share your configuration, you can certainly use the `ConfigSingleton` class.
Moreover, pac4j now handles authorization so you can certainly remove Deadbolt and use the `authorizerName` parameter.

**Comment by PR-O** [comment]
I will try the ConfigSingleton approach. Thanks.

And we are definitely planning on migrating our Deadbolt logic to Pac4J ;). One adventure at a time.

**Comment by PR-O** [comment]
When I use the ConfigSingleton class to obtain the pac4j config like so:

    Config authConfig = ConfigSingleton.getConfig();

I get an empty config.

Is there a special way to get a hold of the config this way?

**Comment by leleuj** [comment]
You must first do a: `ConfigSingleton.setConfig(config);` in your SecurityModules for example.

**Comment by PR-O** [comment]
Understood. I've added it to the SecurityModule.

Thanks!

**Comment by leleuj** [comment]
Keep us posted about the authorizations part...
