### ISSUE TITLE
Rename RequiresAuthentication* as Security*

### ISSUE THREAD

**Issue by leleuj** [pac4j/play-pac4j#93]

**Comment by leleuj** [comment]
@hugovalk : as we are about to add a `SecurityFilter`, I think existing components should be renamed with the same pattern. For example: `RequiresAuthenticationAction` becoming `SecurityAction`.

Speaking of which, the `clientName` and `authorizerName` parameters should become `clients` and `authorizers`.

**Comment by hugovalk** [comment]
Good suggestions. At least `clientName` and `authorizerName` should have been plural. But the shorter form `clients` and `authorizers` is better. 

As for `SecurityAction` I would suggest refactoring this a bit, by using Action Composition and a request wrapper, see: 
https://www.playframework.com/documentation/2.4.x/ScalaActionsComposition

We could call it: `AuthenticatedAction` meaning an action where the user has been authenticated. Then you would be able to get the user profile by: `request.getUserProfile`. This works by wrapping the request. Read the link above for more info.

**Comment by leleuj** [comment]
About the `AuthenticatedAction` name, it lacks the authorization part. That's why I think `SecurityAction` is better.

The current Scala action provides the profile without interacting with the request: isn't it better?

```
def facebookIndex = RequiresAuthentication("FacebookClient") { profile =>
    Action { request =>
      Ok(views.html.protectedIndex(profile))
    }
  }
```

How would you rewrite that using action composition?

**Comment by hugovalk** [comment]
What about the name `SecureAction`? 

I think with Action composition we might be able to refactor it to be used like: 

    def facebookIndex = SecureAction("FacebookClient") { request =>
      Ok(views.html.protectedIndex(request.getUserProfile))
      // or
      Ok(views.html.protectedIndex(request.user)
    }

This would be more similar to:

    request.getUserPrincipal() // In Java servlet applications.

**Comment by leleuj** [comment]
OK. It looks better in name and code.

**Comment by leleuj** [comment]
Let's give it a try...

**Comment by leleuj** [comment]
@hugovalk : still planning to do the renaming?

**Comment by leleuj** [comment]
Re-planned to 2.2.0
