### ISSUE TITLE
Remove UserProfileController

### ISSUE THREAD

**Issue by leleuj** [pac4j/play-pac4j#94]
The value of the `UserProfileController` is fairly low: just one method `getUserProfile` to retrieve the current user profile.
To be consistent with other pac4j implementations (which don't have such element), it wold make sense to remove it.

**Comment by leleuj** [comment]
@hugovalk : what do you think of this one?

**Comment by hugovalk** [comment]
How would we get access to the user profile in the Java demo application? 

Maybe we can make use of action composition:
https://www.playframework.com/documentation/2.2.x/JavaActionsComposition#Authentication

However, it seems to be less powerful than the Scala variant.

**Comment by leleuj** [comment]
Like in any other pac4j library: context -> manager -> user profile

```
PlayWebContext context = new PlayWebContext(ctx(), config.getSessionStore());
ProfileManager manager = new ProfileManager(context);
UserProfile profile = manager.get(true);
```

Here, it's true that you need to also inject the `config`. Maybe we should keep the userprofile.

Action composition is what we already use for the `RequiresAuthentication` annotation and `RequiresAuthenticationAction` action.

**Comment by hugovalk** [comment]
Another suggestion might be to rename it to `UserProfileProvider` which can be injected in the controllers. Then you get rid of the inheritance in favor of composition which is good practice.

**Comment by leleuj** [comment]
Can you elaborate a little more on how we would use this injected `UserProfileProvider`?

**Comment by hugovalk** [comment]
The only method in `UserProfileController` does not have anything to do with controllers, just with getting the user profile. So rename it to UserProfileProvider and rename the method to `get()`. 

Use it like this (Java):

    public class MyController extends Controller {
        @Inject
        private UserProfilePovider userProfile;
        ...
            CommonProfile profile = userProfile.get()
        ....
    }

or Scala:

    class MyController @Inject() (userProfile: UserProfileProvider) extends Controller {
      ...
        userProfile.get
    }

Preferably I would love it for Scala to return an `Option[CommonProfile]`

**Comment by leleuj** [comment]
But you need the Play `ctx()` to build the web context and profile manager to get the user profile, don't you? And this `ctx()` is only available in controllers.

Speaking of the `Option`, notice that pac4j v1.9 will be Java 8 and all play-pac4j versions based on it will be Java 8 as well.

**Comment by hugovalk** [comment]
In the Scala `Security` trait, this is not necessary, so maybe this could be done for the UserProfileProvider as well:

    protected def getUserProfile(request: RequestHeader): P = {
      val webContext = new PlayWebContext(request, config.getSessionStore)
      val profileManager = new ProfileManager[P](webContext)
      profileManager.get(true)
    }

**Comment by leleuj** [comment]
Beyond implementation, do you think the `UserProfileController` or `UserProfileProvider` is necessary for play-pac4j users or we can remove it (and let users use the web context and profile manager)?

**Comment by hugovalk** [comment]
Must users then always use this code like in the snippet from my previous comment? I feel (until convinced otherwise) that the web context and profile manager are more about the inner workings of play-pac4j. 

At this moment user code does not contain the web context and/or the profile manager. By keeping it this way, we would have more flexibility in refactoring later on.

**Comment by leleuj** [comment]
OK. Let's keep this logic internal for now and let's try the composition approach as you proposed.

**Comment by leleuj** [comment]
@hugovalk : something to propose on this one or do we close it?

**Comment by leleuj** [comment]
Re-planned to 2.2.0
